<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>chapter_3 – Kiran M Aralikatti</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.ico" rel="icon">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3a6427571ecaa27ae948310bf21e5415.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Kiran M Aralikatti</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../publications.qmd"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.qmd"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notes.qmd"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/kiranaralikatti"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">GitHub</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://linkedin.com/in/kiranaralikatti"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text">LinkedIn</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#trajectory-optimization-using-deep-neural-network" id="toc-trajectory-optimization-using-deep-neural-network" class="nav-link active" data-scroll-target="#trajectory-optimization-using-deep-neural-network">Trajectory Optimization using Deep Neural Network</a>
  <ul class="collapse">
  <li><a href="#physics-informed-neural-networks-architecture" id="toc-physics-informed-neural-networks-architecture" class="nav-link" data-scroll-target="#physics-informed-neural-networks-architecture">Physics-Informed Neural Networks Architecture</a>
  <ul class="collapse">
  <li><a href="#pinn-formulation" id="toc-pinn-formulation" class="nav-link" data-scroll-target="#pinn-formulation">PINN Formulation</a></li>
  <li><a href="#loss-function-of-pinns" id="toc-loss-function-of-pinns" class="nav-link" data-scroll-target="#loss-function-of-pinns">Loss Function of PINNs</a></li>
  <li><a href="#network-architecture" id="toc-network-architecture" class="nav-link" data-scroll-target="#network-architecture">Network Architecture</a></li>
  <li><a href="#training-procedure" id="toc-training-procedure" class="nav-link" data-scroll-target="#training-procedure">Training Procedure</a></li>
  <li><a href="#solving-coupled-odes" id="toc-solving-coupled-odes" class="nav-link" data-scroll-target="#solving-coupled-odes">Solving Coupled ODEs</a></li>
  <li><a href="#advantages-and-challenges" id="toc-advantages-and-challenges" class="nav-link" data-scroll-target="#advantages-and-challenges">Advantages and Challenges</a></li>
  </ul></li>
  <li><a href="#odes-solution-using-pinns" id="toc-odes-solution-using-pinns" class="nav-link" data-scroll-target="#odes-solution-using-pinns">ODEs Solution using PINNs</a>
  <ul class="collapse">
  <li><a href="#scalar-trajectory-optimization" id="toc-scalar-trajectory-optimization" class="nav-link" data-scroll-target="#scalar-trajectory-optimization">Scalar Trajectory Optimization</a></li>
  <li><a href="#linear-tangent-steering-problem" id="toc-linear-tangent-steering-problem" class="nav-link" data-scroll-target="#linear-tangent-steering-problem">Linear Tangent Steering Problem</a></li>
  <li><a href="#tanh-activation-function" id="toc-tanh-activation-function" class="nav-link" data-scroll-target="#tanh-activation-function">Tanh Activation Function</a></li>
  <li><a href="#rowdy-adaptive-activation-function-raaf" id="toc-rowdy-adaptive-activation-function-raaf" class="nav-link" data-scroll-target="#rowdy-adaptive-activation-function-raaf">Rowdy Adaptive Activation Function (RAAF)</a></li>
  </ul></li>
  <li><a href="#linear-tangent-steering-problem-1" id="toc-linear-tangent-steering-problem-1" class="nav-link" data-scroll-target="#linear-tangent-steering-problem-1">Linear Tangent Steering Problem</a>
  <ul class="collapse">
  <li><a href="#pinns-method" id="toc-pinns-method" class="nav-link" data-scroll-target="#pinns-method">PINNs Method</a></li>
  <li><a href="#weights-initialization-and-interpolation" id="toc-weights-initialization-and-interpolation" class="nav-link" data-scroll-target="#weights-initialization-and-interpolation">Weights Initialization and Interpolation</a></li>
  <li><a href="#effect-of-activation-function-on-model-performance" id="toc-effect-of-activation-function-on-model-performance" class="nav-link" data-scroll-target="#effect-of-activation-function-on-model-performance">Effect of Activation Function on Model Performance</a></li>
  <li><a href="#simplified-lts-model-with-trainable-parameters" id="toc-simplified-lts-model-with-trainable-parameters" class="nav-link" data-scroll-target="#simplified-lts-model-with-trainable-parameters">Simplified LTS Model with Trainable Parameters</a></li>
  <li><a href="#limitations-with-the-pinns-method-for-ocp" id="toc-limitations-with-the-pinns-method-for-ocp" class="nav-link" data-scroll-target="#limitations-with-the-pinns-method-for-ocp">Limitations with the PINNs Method for OCP</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/kiranaralikatti/edit/main/DNN_Pipeline_for_TO/chapter_3.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/kiranaralikatti/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><h1 class="title display-7"></h1></header><div class="quarto-title-block"><div class="quarto-title-tools-only"><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>




<section id="trajectory-optimization-using-deep-neural-network" class="level1">
<h1>Trajectory Optimization using Deep Neural Network</h1>
<section id="physics-informed-neural-networks-architecture" class="level2">
<h2 class="anchored" data-anchor-id="physics-informed-neural-networks-architecture">Physics-Informed Neural Networks Architecture</h2>
<p>Physics-Informed Neural Networks (PINNs) are a class of deep learning models designed to solve ordinary and partial differential equations (ODEs and PDEs) by incorporating physical laws directly into the neural network training process. Unlike traditional numerical methods that rely on mesh-based discretization, PINNs embed the governing equations as soft constraints into the loss function, enabling mesh-free, data-efficient, and interpretable solutions <span class="citation" data-cites="raissi2019physics karniadakis2021physics">[@raissi2019physics; @karniadakis2021physics]</span>.</p>
<p>The key idea behind PINNs is to construct a neural network that approximates the solution to a differential equation while minimizing a composite loss function. This loss typically includes two components: (i) the residuals of the governing equations, which enforce the physical constraints, and (ii) the error at initial and boundary conditions. By training the network to reduce these terms simultaneously, PINNs produce solutions that respect both data and physics.</p>
<p>PINNs offer significant advantages in solving complex and high-dimensional problems in fields such as fluid dynamics, heat conduction, elasticity, and optimal control <span class="citation" data-cites="cuomo2022scientific">[@cuomo2022scientific]</span>. Their ability to encode prior knowledge in the form of differential operators improves generalization and stability, especially when observational data are sparse or noisy. Recent advances have extended PINNs to handle stiff systems, multi-physics problems, and inverse modeling tasks, showcasing their versatility and growing importance in scientific computing <span class="citation" data-cites="wang2021understanding mao2020physics">[@wang2021understanding; @mao2020physics]</span>. Furthermore, innovations in adaptive activation functions, domain decomposition, and transfer learning continue to enhance their accuracy and scalability <span class="citation" data-cites="mcclenny2020self shukla2021parallel">[@mcclenny2020self; @shukla2021parallel]</span>.</p>
<section id="pinn-formulation" class="level3">
<h3 class="anchored" data-anchor-id="pinn-formulation">PINN Formulation</h3>
<p>Consider a general first-order system of ordinary differential equations given by:</p>
<p><span id="eq-ch3-pinn-ode"><span class="math display">\[
\dot{\mathbf{x}}(t) = \mathbf{f}(\mathbf{x}(t), t), \quad t \in [0, t_f],
\tag{1}\]</span></span></p>
<p>where <span class="math inline">\(\mathbf{x}(t) \in \mathbb{R}^n\)</span> is the state vector, and <span class="math inline">\(\mathbf{f} : \mathbb{R}^n \times \mathbb{R} \rightarrow \mathbb{R}^n\)</span> is a known (possibly nonlinear) function describing the system dynamics. The system is subject to an initial condition:</p>
<p><span id="eq-ch3-pinn-ic"><span class="math display">\[
\mathbf{x}(0) = \mathbf{x}_0.
\tag{2}\]</span></span></p>
<p>In the PINN framework, the solution <span class="math inline">\(\mathbf{x}(t)\)</span> is approximated by a neural network <span class="math inline">\(\mathbf{x}_{\theta}(t)\)</span>, where <span class="math inline">\(\theta\)</span> represents the trainable parameters of the network.</p>
</section>
<section id="loss-function-of-pinns" class="level3">
<h3 class="anchored" data-anchor-id="loss-function-of-pinns">Loss Function of PINNs</h3>
<p>The total loss function used to train the PINN is composed of two terms: the residual loss and the initial condition loss. It is defined as:</p>
<p><span id="eq-ch3-pinn-loss"><span class="math display">\[
\mathcal{L}_{\text{PINN}} = \omega_1 \mathcal{L}_{\text{residual}} + \omega_2 \mathcal{L}_{\text{IC}},
\tag{3}\]</span></span></p>
<p>where <span class="math inline">\(\omega_1\)</span> and <span class="math inline">\(\omega_2\)</span> are weighting coefficients that balance the enforcement of the system dynamics and the initial condition, where <span class="math inline">\(\sum_{i=0}^{N}\omega_i = 1\)</span></p>
<p>The residual loss is computed over a set of <span class="math inline">\(N\)</span> collocation points <span class="math inline">\(\{t_i\}_{i=1}^{N} \subset [0, t_f]\)</span>:</p>
<p><span id="eq-ch3-residual-loss"><span class="math display">\[
\mathcal{L}_{\text{residual}} = \frac{1}{N} \sum_{i=1}^{N} \left\| \frac{d}{dt} \mathbf{x}_{\theta}(t_i) - \mathbf{f}(\mathbf{x}_{\theta}(t_i), t_i) \right\|^2.
\tag{4}\]</span></span></p>
<p>The initial condition loss ensures that the predicted trajectory starts at the correct initial value:</p>
<p><span id="eq-ch3-ic-loss"><span class="math display">\[
\mathcal{L}_{\text{IC}} = \left\| \mathbf{x}_{\theta}(0) - \mathbf{x}_0 \right\|^2.
\tag{5}\]</span></span></p>
<p>This formulation ensures that the learned function <span class="math inline">\(\mathbf{x}_{\theta}(t)\)</span> adheres to both the physics (via the ODE residual) and the given initial condition.</p>
</section>
<section id="network-architecture" class="level3">
<h3 class="anchored" data-anchor-id="network-architecture">Network Architecture</h3>
<p>A typical PINN architecture consists of:</p>
<ul>
<li><strong>Input Layer:</strong> Receives input variables such as time, spatial coordinates, or parameters.</li>
<li><strong>Hidden Layers:</strong> Multiple fully connected layers using nonlinear activation functions such as Tanh or ReLU to learn the functional mapping.</li>
<li><strong>Output Layer:</strong> Produces the predicted solution <span class="math inline">\(\mathbf{x}_{\theta}(t) \in \mathbb{R}^n\)</span>.</li>
</ul>
<p>This architecture is flexible and can be adapted to accommodate multiple outputs, complex nonlinearities, or additional inputs such as control parameters or auxiliary variables.</p>
</section>
<section id="training-procedure" class="level3">
<h3 class="anchored" data-anchor-id="training-procedure">Training Procedure</h3>
<p>Training a PINN involves minimizing the loss function <span class="math inline">\(\mathcal{L}_{\text{PINN}}\)</span> using gradient-based optimization methods such as stochastic gradient descent (SGD) or Adam. The time derivatives of the neural network outputs are computed via automatic differentiation. During each iteration, gradients of the loss with respect to the network parameters <span class="math inline">\(\theta\)</span> are computed and used to update the model. The goal is to simultaneously minimize the equation residuals and enforce the boundary/initial conditions.</p>
<div id="fig-ch3-pinn-architecture" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch3-pinn-architecture-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_imgs/pinn_model.PNG" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ch3-pinn-architecture-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: PINNs architecture <span class="citation" data-cites="cuomo2022scientific">[@cuomo2022scientific]</span>
</figcaption>
</figure>
</div>
</section>
<section id="solving-coupled-odes" class="level3">
<h3 class="anchored" data-anchor-id="solving-coupled-odes">Solving Coupled ODEs</h3>
<p>Coupled ODE systems frequently appear in scientific and engineering contexts such as trajectory optimization, chemical kinetics and multi-body dynamics. These systems consist of multiple interdependent differential equations that must be solved simultaneously.</p>
<p>PINNs handle coupled systems by using a NN with multiple outputs corresponding to each component of the state vector. The residuals of all coupled equations are computed and minimized together, while initial or boundary conditions for each state variable are incorporated into the loss function. This approach enables the network to learn solutions that satisfy the entire coupled system consistently.</p>
</section>
<section id="advantages-and-challenges" class="level3">
<h3 class="anchored" data-anchor-id="advantages-and-challenges">Advantages and Challenges</h3>
<p>PINNs offer several advantages. By embedding prior physical knowledge, PINNs significantly reduce the need for large labeled datasets, thereby improving data efficiency <span class="citation" data-cites="raissi2019physics karniadakis2021physics">[@raissi2019physics; @karniadakis2021physics]</span>. Moreover, the solutions produced are physically consistent, which enhances generalization, even in regions beyond the training data <span class="citation" data-cites="cuomo2022scientific">[@cuomo2022scientific]</span>. Another key benefit is their mesh-free nature, eliminating the need for mesh generation or discretization, which simplifies implementation for complex geometries <span class="citation" data-cites="raissi2019physics">[@raissi2019physics]</span>.</p>
<p>Despite these benefits, several challenges remain. Training PINNs for stiff or highly nonlinear systems often suffers from gradient imbalance and instability, which can impede convergence <span class="citation" data-cites="wang2021understanding lu2021deepxde">[@wang2021understanding; @lu2021deepxde]</span>. Additionally, selecting appropriate weighting factors for different loss components, such as residual and boundary condition losses, is nontrivial and can significantly affect performance <span class="citation" data-cites="mcclenny2020self">[@mcclenny2020self]</span>. The computational cost is another consideration, as training deep neural networks with automatic differentiation can be resource-intensive and time-consuming <span class="citation" data-cites="shukla2021parallel">[@shukla2021parallel]</span>.</p>
<p>Recent advances have addressed some of these challenges through methods such as adaptive activation functions, residual-based adaptive sampling, transfer learning, and domain decomposition, which improve training stability and efficiency <span class="citation" data-cites="mcclenny2020self shukla2021parallel lu2021deepxde">[@mcclenny2020self; @shukla2021parallel; @lu2021deepxde]</span>.</p>
</section>
</section>
<section id="odes-solution-using-pinns" class="level2">
<h2 class="anchored" data-anchor-id="odes-solution-using-pinns">ODEs Solution using PINNs</h2>
<section id="scalar-trajectory-optimization" class="level3">
<h3 class="anchored" data-anchor-id="scalar-trajectory-optimization">Scalar Trajectory Optimization</h3>
<p>We consider an optimal control problem given in <span class="citation" data-cites="pinch1995optimal">[@pinch1995optimal]</span> example 4.3, involving a linear first-order dynamical system, where the state <span class="math inline">\(x(t)\)</span> evolves according to the control input <span class="math inline">\(u(t)\)</span> through the relation <span class="math inline">\(\dot{x}(t) = -x(t) + u(t)\)</span>. The goal is to drive the system from the initial condition <span class="math inline">\(x(0) = 0\)</span> to the final state <span class="math inline">\(x(1) = 2\)</span> over the fixed time interval <span class="math inline">\(t \in [0, 1]\)</span>. To achieve this, we aim to determine the optimal control <span class="math inline">\(u(t)\)</span> that minimizes the quadratic cost functional, which penalizes both the magnitude of the state and the control effort over time. This cost functional captures the trade-off between maintaining the state close to the origin and minimizing the energy or effort required for control.</p>
<p>The system dynamics, boundary conditions, and cost functional are given as:</p>
<p><span id="eq-ch3-scalar-problem"><span class="math display">\[
\begin{aligned}
\dot{x}(t) &amp;= -x(t) + u(t), &amp;&amp; \text{(System dynamics)} \\
x(0) &amp;= 0, \quad x(1) = 2, &amp;&amp; \text{(Boundary conditions)} \\
J &amp;= \frac{1}{2} \int_0^1 \left( 3x^2(t) + u^2(t) \right) \, dt. &amp;&amp; \text{(Cost functional)}
\end{aligned}
\tag{6}\]</span></span></p>
<p>The Hamiltonian</p>
<p><span id="eq-ch3-scalar-hamiltonian"><span class="math display">\[
H = \frac{3}{2} x^2 + \frac{1}{2} u^2 + \lambda (-x + u).
\tag{7}\]</span></span></p>
<p>There is no constraint on <span class="math inline">\(u\)</span>, so to maximize <span class="math inline">\(H\)</span> we consider <span class="math inline">\(\frac{\partial H}{\partial u}\)</span>.</p>
<p><span id="eq-ch3-scalar-hu"><span class="math display">\[
\frac{\partial H}{\partial u} = -u + \lambda \quad \text{and} \quad \frac{\partial^2 H}{\partial u^2} = -1.
\tag{8}\]</span></span></p>
<p>So <span class="math inline">\(H\)</span> is maximized when <span class="math inline">\(u = \lambda\)</span> and the corresponding state equation is</p>
<p><span id="eq-ch3-scalar-state-ode"><span class="math display">\[
\dot{x} = -x + \lambda
\tag{9}\]</span></span></p>
<p>and <span class="math inline">\(\lambda\)</span> satisfies</p>
<p><span id="eq-ch3-scalar-costate-ode"><span class="math display">\[
\dot{\lambda} = -\frac{\partial H}{\partial x} = 3x + \lambda.
\tag{10}\]</span></span></p>
<p>Thus, <span class="math inline">\(\ddot{x} = 4x\)</span> and <span class="math inline">\(\lambda = \dot{x} + x\)</span>, giving</p>
<p><span id="eq-ch3-scalar-x-sol"><span class="math display">\[
x = A \sinh(2t + \alpha)
\tag{11}\]</span></span></p>
<p>and</p>
<p><span id="eq-ch3-scalar-lambda"><span class="math display">\[
\lambda = u^* = A\left(2 \cosh(2t + \alpha) + \sinh(2t + \alpha)\right).
\tag{12}\]</span></span></p>
<p>The end conditions on <span class="math inline">\(x\)</span> give <span class="math inline">\(\alpha = 0\)</span> and <span class="math inline">\(A = 2/\sinh 2\)</span>. Thus, the optimal control is</p>
<p><span id="eq-ch3-scalar-u-optimal"><span class="math display">\[
u^* = \frac{2(2 \cosh 2t + \sinh 2t)}{\sinh 2}.
\tag{13}\]</span></span></p>
<p><span id="eq-ch3-scalar-state-costate"><span class="math display">\[
\begin{aligned}
\dot{x}(t) = -x(t) + \lambda(t), &amp;&amp; \text{(State ODE)}\\
\dot{\lambda}(t) = 3x(t) + \lambda(t), &amp;&amp; \text{(Costate ODE)}\\
\end{aligned}
\tag{14}\]</span></span></p>
<section id="loss-function" class="level4">
<h4 class="anchored" data-anchor-id="loss-function">Loss Function</h4>
<p>In the PINNs framework, the state and costate equations are enforced through a loss that penalizes both the ODE residuals and the boundary conditions.</p>
<p><strong>Residual Loss.</strong></p>
<p><span id="eq-ch3-scalar-residual"><span class="math display">\[
\mathcal{L}_{\text{residual}} = \frac{1}{N} \sum_{i=1}^{N}
\Big[ \big( \dot{x}_i + x_i - \lambda_i \big)^2
+ \big( \dot{\lambda}_i - 3x_i - \lambda_i \big)^2 \Big],
\tag{15}\]</span></span></p>
<p><strong>Boundary Condition Loss.</strong></p>
<p><span id="eq-ch3-scalar-bc"><span class="math display">\[
\mathcal{L}_{\text{BC}} = \tfrac{1}{2}(x(0)-0)^2 + (x(1)-2)^2,
\tag{16}\]</span></span></p>
<p><strong>Total Loss.</strong></p>
<p><span id="eq-ch3-scalar-total-loss"><span class="math display">\[
\mathcal{L}_{\text{PINN}} = w_1 \mathcal{L}_{\text{residual}} + w_2 \mathcal{L}_{\text{BC}},
\qquad \sum_{i=1}^{m} w_i = 1.
\tag{17}\]</span></span></p>
</section>
</section>
<section id="linear-tangent-steering-problem" class="level3">
<h3 class="anchored" data-anchor-id="linear-tangent-steering-problem">Linear Tangent Steering Problem</h3>
<p>As explained in Section 2.3, the Linear Tangent Steering (LTS) problem is a time-optimal control problem that aims to minimize the transfer time of the vehicle while satisfying the system dynamics and boundary conditions.</p>
<section id="hyperparameters" class="level4">
<h4 class="anchored" data-anchor-id="hyperparameters">Hyperparameters</h4>
<p>The PINNs model employs a fully connected feedforward neural network with 2 hidden layers, each containing 8 neurons. Training is conducted using the Adam optimizer with an initial learning rate of <span class="math inline">\(10^{-3}\)</span> over initial 1750 iterations and for next iterations 250 L-BFGS is employed. The total loss function uses weights <span class="math inline">\(w_1 = 0.1\)</span> and <span class="math inline">\(w_2 = 0.9\)</span> to prioritize boundary conditions. The model is trained with 100 domain collocation points and 2 boundary points at <span class="math inline">\(t = 0\)</span> and <span class="math inline">\(t\)</span>. The architecture of the PINN designed for this problem is shown in <a href="#fig-ch3-pinn-scalar" class="quarto-xref">Figure&nbsp;2</a>.</p>
<div id="fig-ch3-pinn-scalar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch3-pinn-scalar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_imgs/c22.PNG" class="img-fluid figure-img" style="width:55.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ch3-pinn-scalar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: PINNs Architecture for scalar problem
</figcaption>
</figure>
</div>
</section>
</section>
<section id="tanh-activation-function" class="level3">
<h3 class="anchored" data-anchor-id="tanh-activation-function">Tanh Activation Function</h3>
<p>The accuracy depends on the number of trainable parameters, so the number of the trainable parameters in the given architecture for Tanh activation function is given by the below calculation:</p>
<p>For each layer in the network:</p>
<p><span id="eq-ch3-param-count"><span class="math display">\[
\begin{aligned}
\text{Number of Weights} &amp;= n_\text{current} \times n_\text{next}, \\
\text{Number of Biases} &amp;= n_\text{next}, \\
\text{Number of Parameters} &amp;= \text{Number of Weights} + \text{Number of Biases}.
\end{aligned}
\tag{18}\]</span></span></p>
<p>where <span class="math inline">\(n_\text{current} =\)</span> number of nodes in current layer and <span class="math inline">\(n_\text{next} =\)</span> number of nodes in next layer.</p>
<p>The total number of trainable parameters is the sum of the parameters across all layers.</p>
<div id="tbl-ch3-trainable-tanh" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch3-trainable-tanh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Trainable Parameters per Layer (Tanh)
</figcaption>
<div aria-describedby="tbl-ch3-trainable-tanh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 27%">
<col style="width: 25%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Layer</th>
<th style="text-align: center;">No of Weights</th>
<th style="text-align: center;">No of Biases</th>
<th style="text-align: center;">Total Parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Input to <span class="math inline">\(1^{st}\)</span> Hidden Layer</td>
<td style="text-align: center;"><span class="math inline">\(1 \times 16 = 16\)</span></td>
<td style="text-align: center;"><span class="math inline">\(16\)</span></td>
<td style="text-align: center;"><span class="math inline">\(16 + 16 = 32\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(1^{st}\)</span> Hidden to <span class="math inline">\(2^{nd}\)</span> Hidden Layer</td>
<td style="text-align: center;"><span class="math inline">\(16 \times 16 = 256\)</span></td>
<td style="text-align: center;"><span class="math inline">\(16\)</span></td>
<td style="text-align: center;"><span class="math inline">\(256 + 16 = 272\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(2^{nd}\)</span> Hidden to Output Layer</td>
<td style="text-align: center;"><span class="math inline">\(16 \times 2 = 32\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(32 + 2 = 34\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: center;"><span class="math inline">\(16 + 256 + 32 = 304\)</span></td>
<td style="text-align: center;"><span class="math inline">\(16 + 16 + 2 = 34\)</span></td>
<td style="text-align: center;"><span class="math inline">\(32 + 272 + 34 = 338\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Thus, the total number of trainable parameters in the network is <span class="math inline">\(338\)</span>.</p>
<p>Using the same network configuration with a Tanh activation function, the training process yielded a total loss of <span class="math inline">\(\mathcal{L} = 1.038 \times 10^{-4}\)</span>. When compared against the analytical solution, the Root Mean Square (RMS) errors for the state and costate variables are <span class="math inline">\(2.44 \times 10^{-3}\)</span> and <span class="math inline">\(3.64 \times 10^{-3}\)</span>. These results confirm the efficacy of the chosen network architecture and highlight the capability of the Tanh activation function in approximating the solution with a certain level of accuracy.</p>
</section>
<section id="rowdy-adaptive-activation-function-raaf" class="level3">
<h3 class="anchored" data-anchor-id="rowdy-adaptive-activation-function-raaf">Rowdy Adaptive Activation Function (RAAF)</h3>
<p>The development of sophisticated neural network architectures has been pivotal in advancing complex machine learning applications. One such innovation is the RAAF <span class="citation" data-cites="ccelik2024optimal">[@ccelik2024optimal]</span>, designed to enhance the learning capability and generalization power of neural networks by integrating adaptive and oscillatory properties into traditional activation functions. This function introduces a novel approach to balancing expressiveness and training stability, utilizing modifications of standard activations such as the Tanh function.</p>
<section id="modified-tanh-function" class="level4">
<h4 class="anchored" data-anchor-id="modified-tanh-function">Modified Tanh Function</h4>
<p>At the core of RAAF lies a modified Tanh function, mathematically expressed as:</p>
<p><span id="eq-ch3-modified-tanh"><span class="math display">\[
\sigma(x; \alpha) = \frac{e^{\alpha x} - e^{-\alpha x}}{e^{\alpha x} + e^{-\alpha x}},
\tag{19}\]</span></span></p>
<p>where <span class="math inline">\(\alpha\)</span> is a trainable parameter that scales the input, providing flexibility in the activation behavior. By allowing <span class="math inline">\(\alpha\)</span> to adapt during training, the network gains additional capacity to capture complex patterns in data. This adaptive feature accelerates convergence, particularly in the early training stages, by reshaping the gradient landscape to avoid saturation.</p>
</section>
<section id="rowdy-adaptive-activation-function" class="level4">
<h4 class="anchored" data-anchor-id="rowdy-adaptive-activation-function">Rowdy Adaptive Activation Function</h4>
<p>RAAF <span class="citation" data-cites="jagtap2022deep">[@jagtap2022deep]</span> extends this concept by combining the modified Tanh function with trigonometric terms, introducing oscillatory components that enrich the activation function’s representational diversity:</p>
<p><span id="eq-ch3-raaf"><span class="math display">\[
\sigma_{\text{rowdy}}(x) = \sigma_{\text{base}}(x; \alpha) + \sum_{k=1}^N \beta_k \sin(k \omega x),
\tag{20}\]</span></span></p>
<p>where: <span class="math inline">\(\sigma_{\text{base}}(x; \alpha)\)</span> represents the adaptive Tanh function. <span class="math inline">\(\beta_k\)</span> and <span class="math inline">\(\omega\)</span> are trainable parameters that control the amplitude and frequency of the oscillations.</p>
<p>This design ensures smoother loss landscapes during training, reducing the risk of convergence to local minima. The oscillatory components are particularly useful in handling high-frequency variations in the data, enabling the model to generalize effectively across diverse input distributions.</p>
<p>For each layer in the network:</p>
<p><span id="eq-ch3-raaf-param-count"><span class="math display">\[
\begin{aligned}
\text{Number of Weights} &amp;= n_\text{current} \times n_\text{next}, \\
\text{Number of Biases} &amp;= n_\text{next}, \\
\text{Number of Parameters} &amp;= \text{Weights} + \text{Biases}.
\end{aligned}
\tag{21}\]</span></span></p>
<p>where <span class="math inline">\(n_\text{current} =\)</span> number of nodes in current layer and <span class="math inline">\(n_\text{next} =\)</span> number of nodes in next layer.</p>
<p>Additionally, the RAAF adds:</p>
<p><span id="eq-ch3-raaf-extra"><span class="math display">\[
\text{Parameters}_\text{rowdy} = n_\text{hidden} \times \text{RAAF parameters}
\tag{22}\]</span></span></p>
<p>for each neuron in the hidden layers.</p>
<p>The total number of trainable parameters is the sum of all weights, biases, and RAAF-specific parameters.</p>
<div id="tbl-ch3-trainable-raaf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch3-trainable-raaf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Trainable Parameters per Layer (RAAF)
</figcaption>
<div aria-describedby="tbl-ch3-trainable-raaf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 23%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Layers</th>
<th style="text-align: center;">No of Weights</th>
<th style="text-align: center;">No of Biases</th>
<th style="text-align: center;">RAAF Parameters</th>
<th style="text-align: center;">Total Parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I/P to Hidden Layer</td>
<td style="text-align: center;"><span class="math inline">\(1 \times 20 = 20\)</span></td>
<td style="text-align: center;"><span class="math inline">\(20\)</span></td>
<td style="text-align: center;"><span class="math inline">\(20 \times 3 = 60\)</span></td>
<td style="text-align: center;"><span class="math inline">\(20 + 20 + 60 = 100\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Hidden to O/P Layer</td>
<td style="text-align: center;"><span class="math inline">\(20 \times 2 = 40\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(40 + 2 + 0 = 42\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: center;"><span class="math inline">\(60\)</span></td>
<td style="text-align: center;"><span class="math inline">\(22\)</span></td>
<td style="text-align: center;"><span class="math inline">\(60\)</span></td>
<td style="text-align: center;"><span class="math inline">\(142\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Thus, the total number of trainable parameters in the network is: 142</p>
<p>Using the RAAF with one hidden layer and 20 nodes in the hidden layer, the training process achieved a total loss of <span class="math inline">\(\mathcal{L} = 4.19 \times 10^{-5}\)</span>. When compared to the analytical solution, the RMS errors for the state and costate variables were <span class="math inline">\(6.54 \times 10^{-5}\)</span> and <span class="math inline">\(5.84 \times 10^{-5}\)</span>. These results demonstrate the effectiveness of the RAAF in improving the accuracy of the solution while maintaining robust convergence properties with less number of trainable parameters.</p>
<div id="fig-ch3-raaf-solution" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch3-raaf-solution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_imgs/comp_tah_rowdy.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ch3-raaf-solution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: PINNs Solution using RAAF
</figcaption>
</figure>
</div>
<div id="fig-ch3-error-comparison" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch3-error-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ch3-error-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ch3-tanh-error" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ch3-tanh-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_imgs/tanh_error.png" class="img-fluid figure-img" data-ref-parent="fig-ch3-error-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ch3-tanh-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Total Error: Tanh.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ch3-error-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ch3-raaf-error" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ch3-raaf-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_imgs/RAAF_error.png" class="img-fluid figure-img" data-ref-parent="fig-ch3-error-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ch3-raaf-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Total Error: RAAF.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ch3-error-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Comparison of the Total errors.
</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="linear-tangent-steering-problem-1" class="level2">
<h2 class="anchored" data-anchor-id="linear-tangent-steering-problem-1">Linear Tangent Steering Problem</h2>
<section id="pinns-method" class="level3">
<h3 class="anchored" data-anchor-id="pinns-method">PINNs Method</h3>
<section id="objective-function-and-hamiltonian-derivation" class="level4">
<h4 class="anchored" data-anchor-id="objective-function-and-hamiltonian-derivation">Objective Function and Hamiltonian Derivation</h4>
<p>The objective of the LTS problem is to minimize the final time <span class="math inline">\(t_f\)</span>. Thus, the performance index (objective function) is:</p>
<p><span id="eq-ch3-lts-objective"><span class="math display">\[
J = \int_{0}^{t_f} 1 \, dt = t_f.
\tag{23}\]</span></span></p>
<p>According to Pontryagin’s Maximum Principle, we define the Hamiltonian <span class="math inline">\(\mathcal{H}\)</span> as:</p>
<p><span id="eq-ch3-lts-hamiltonian"><span class="math display">\[
\mathcal{H} = 1 + \lambda_1 \dot{x}_1 + \lambda_2 \dot{x}_2 + \lambda_3 \dot{x}_3 + \lambda_4 \dot{x}_4.
\tag{24}\]</span></span></p>
<p>Substituting the expressions for the state derivatives:</p>
<p><span id="eq-ch3-lts-hamiltonian-sub"><span class="math display">\[
\begin{aligned}
\mathcal{H} &amp;= 1 + \lambda_1 x_3 + \lambda_2 x_4 + \lambda_3 a \cos(u) + \lambda_4 a \sin(u).
\end{aligned}
\tag{25}\]</span></span></p>
</section>
<section id="costate-equations" class="level4">
<h4 class="anchored" data-anchor-id="costate-equations">Costate Equations</h4>
<p>The costate dynamics are obtained from:</p>
<p><span id="eq-ch3-lts-costate-general"><span class="math display">\[
\dot{\lambda}_i = -\frac{\partial \mathcal{H}}{\partial x_i}, \quad i = 1,2,3,4.
\tag{26}\]</span></span></p>
<p>Calculating the partial derivatives:</p>
<p><span id="eq-ch3-lts-costate"><span class="math display">\[
\begin{aligned}
\dot{\lambda}_1 &amp;= -\frac{\partial \mathcal{H}}{\partial x_1} = 0, \\
\dot{\lambda}_2 &amp;= -\frac{\partial \mathcal{H}}{\partial x_2} = 0, \\
\dot{\lambda}_3 &amp;= -\frac{\partial \mathcal{H}}{\partial x_3} = -\lambda_1, \\
\dot{\lambda}_4 &amp;= -\frac{\partial \mathcal{H}}{\partial x_4} = -\lambda_2.
\end{aligned}
\tag{27}\]</span></span></p>
</section>
<section id="optimal-control-law" class="level4">
<h4 class="anchored" data-anchor-id="optimal-control-law">Optimal Control Law</h4>
<p>The optimal control <span class="math inline">\(u^*(t)\)</span> minimizes the Hamiltonian with respect to the control input <span class="math inline">\(u(t)\)</span>:</p>
<p><span id="eq-ch3-lts-optimal-control"><span class="math display">\[
u^*(t) = \arg\min_u \mathcal{H} = \arg\min_u \left( \lambda_3 a \cos(u) + \lambda_4 a \sin(u) \right).
\tag{28}\]</span></span></p>
<p>This expression can be rewritten as:</p>
<p><span id="eq-ch3-lts-hu"><span class="math display">\[
\mathcal{H}_{u} = a \left( \lambda_3 \cos(u) + \lambda_4 \sin(u) \right).
\tag{29}\]</span></span></p>
<p>To minimize <span class="math inline">\(\mathcal{H}_u\)</span>, the optimal control is given by:</p>
<p><span id="eq-ch3-lts-u-optimal"><span class="math display">\[
u^*(t) = \tan^{-1}\left( \frac{\lambda_4(t)}{\lambda_3(t)} \right),
\tag{30}\]</span></span></p>
</section>
<section id="boundary-conditions" class="level4">
<h4 class="anchored" data-anchor-id="boundary-conditions">Boundary Conditions</h4>
<p>The boundary conditions for the LTS problem are:</p>
<ul>
<li><strong>Initial (fixed) conditions:</strong></li>
</ul>
<p><span id="eq-ch3-lts-ic"><span class="math display">\[
x_1(0) = 0, \quad x_2(0) = 0, \quad x_3(0) = 0, \quad x_4(0) = 0
\tag{31}\]</span></span></p>
<ul>
<li><strong>Final (partially fixed) conditions:</strong></li>
</ul>
<p><span id="eq-ch3-lts-fc"><span class="math display">\[
x_2(t_f) = 5, \quad x_3(t_f) = 45, \quad x_4(t_f) = 0
\tag{32}\]</span></span></p>
<ul>
<li><strong>Transversality condition (due to free final state):</strong></li>
</ul>
<p><span id="eq-ch3-lts-transversality"><span class="math display">\[
\lambda_1(t_f) = 0 \quad \text{(since } x_1(t_f) \text{ is free)}
\tag{33}\]</span></span></p>
</section>
<section id="loss-function-for-domain" class="level4">
<h4 class="anchored" data-anchor-id="loss-function-for-domain">Loss Function for Domain</h4>
<p>In the PINNs framework, the domain loss based on the residuals of the state and costate ODEs is defined as:</p>
<p><span id="eq-ch3-lts-domain-loss"><span class="math display">\[
\mathcal{L}_{\text{residual}} = \frac{1}{N}\sum_{i=1}^{N} \left[
\sum_{j=1}^{4} \left( \frac{d x_j}{d t}(t_i) - f_j(\mathbf{x}(t_i), u(t_i)) \right)^2
+ \sum_{j=1}^{4} \left( \frac{d \lambda_j}{d t}(t_i) - g_j(\boldsymbol{\lambda}(t_i)) \right)^2
\right],
\tag{34}\]</span></span></p>
<p>where <span class="math inline">\(f_j\)</span> and <span class="math inline">\(g_j\)</span> denote the right-hand sides of the state and costate ODEs.</p>
</section>
<section id="loss-function-for-boundary-conditions" class="level4">
<h4 class="anchored" data-anchor-id="loss-function-for-boundary-conditions">Loss Function for Boundary Conditions</h4>
<p>The boundary loss enforces the known initial and final values, including the transversality condition:</p>
<p><span id="eq-ch3-lts-bc-loss"><span class="math display">\[
\begin{aligned}
\mathcal{L}_{\text{BC}} = &amp;\frac{1}{4} {\left( x_j(0) - x_{j,0} \right)^2
+ \left( x_2(t_f) - 5 \right)^2
+ \left( x_3(t_f) - 45 \right)^2
+ \left( x_4(t_f) - 0 \right)^2
+ \left( \lambda_1(t_f) \right)^2}
\end{aligned}
\tag{35}\]</span></span></p>
</section>
<section id="total-loss-function" class="level4">
<h4 class="anchored" data-anchor-id="total-loss-function">Total Loss Function</h4>
<p>The complete loss function for training the PINN model becomes:</p>
<p><span id="eq-ch3-lts-total-loss"><span class="math display">\[
\mathcal{L}_{\text{PINN}} = w_1 \mathcal{L}_{\text{residual}} + w_2 \mathcal{L}_{\text{BC}},
\tag{36}\]</span></span></p>
<p>where <span class="math inline">\(w_1 + w_2 = 1\)</span> are hyperparameters controlling the balance between enforcing dynamics and boundary constraints.</p>
</section>
<section id="hyperparameters-tuning" class="level4">
<h4 class="anchored" data-anchor-id="hyperparameters-tuning">Hyperparameters Tuning</h4>
<p>For hyperparameter tuning, the training process employs a total of <span class="math inline">\(30{,}000\)</span> iterations, with a total loss threshold of <span class="math inline">\(10^{-4}\)</span> used as the primary stopping criterion. To enhance stability, a patience mechanism <span class="citation" data-cites="sanchez2018real">[@sanchez2018real]</span> is incorporated: once the loss falls below <span class="math inline">\(10^{-4}\)</span>, training continues for an additional <span class="math inline">\(20\)</span> iterations to ensure the loss consistently remains under the specified threshold.</p>
<p>The training procedure adopts a two-stage Optimization strategy. During the first stage, <span class="math inline">\(90\%\)</span> of the total iterations are executed using the <strong>Adam</strong> optimizer with a learning rate of <span class="math inline">\(10^{-3}\)</span>, allowing for efficient convergence in the initial phase. In the second stage, the remaining <span class="math inline">\(10\%\)</span> of iterations utilize the <strong>L-BFGS</strong> optimizer for fine-tuning. The L-BFGS method is configured with a maximum of <span class="math inline">\(50{,}000\)</span> iterations, a history size of <span class="math inline">\(50\)</span>, and a strong Wolfe line search condition.</p>
<p>This hybrid approach leverages the fast convergence properties of first-order methods during early training, while exploiting the higher accuracy of second-order methods in refining the solution as the loss approaches its minimum.</p>
<p>To place greater emphasis on control within the physics-informed loss, we include the term</p>
<p><span id="eq-ch3-lts-control-loss"><span class="math display">\[
\frac{\partial H}{\partial U} = 0 = -\lambda_3 \sin U + \lambda_4 \cos U
\tag{37}\]</span></span></p>
<p>as part of the loss formulation.</p>
<p>As the analytical solution is available, the error of control is considered for tuning the network parameters. The below diagram shows how the error varied for the Tanh activation function for different number of hidden layers and nodes. The model with 3 hidden layers each with 60 nodes <a href="#fig-ch3-hp-control" class="quarto-xref">Figure&nbsp;5</a> shows the best results, therefore, this model is used for further studies.</p>
<div id="fig-ch3-hp-control" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch3-hp-control-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_imgs/HP_control_diff_total_nodes.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ch3-hp-control-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: MSE error of Control for different nodes and layers
</figcaption>
</figure>
</div>
<div id="tbl-ch3-mse-lts" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch3-mse-lts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Mean Squared Error (MSE) for States, Control, and Final Time
</figcaption>
<div aria-describedby="tbl-ch3-mse-lts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">MSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(x_1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(3.01 \times 10^{-9}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(x_2\)</span></td>
<td style="text-align: right;"><span class="math inline">\(4.44 \times 10^{-9}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(x_3\)</span></td>
<td style="text-align: right;"><span class="math inline">\(5.52 \times 10^{-8}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(x_4\)</span></td>
<td style="text-align: right;"><span class="math inline">\(6.72 \times 10^{-8}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Control <span class="math inline">\(u\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2.34 \times 10^{-5}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Error final Time <span class="math inline">\(\varepsilon_{t_f}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.89 \times 10^{-6}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In the LTS case, careful tuning enabled the network to achieve mean squared errors (MSE) as low as <span class="math inline">\(10^{-5}\)</span> for control. This level of accuracy demonstrates the model’s ability to learn the underlying physics while maintaining smooth and stable control profiles.</p>
</section>
</section>
<section id="weights-initialization-and-interpolation" class="level3">
<h3 class="anchored" data-anchor-id="weights-initialization-and-interpolation">Weights Initialization and Interpolation</h3>
<div id="fig-ch3-interpolation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch3-interpolation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_imgs/inter_process.PNG" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ch3-interpolation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Weight Initialization and Interpolation
</figcaption>
</figure>
</div>
<section id="random-walk-initialization-for-lts-problem" class="level4">
<h4 class="anchored" data-anchor-id="random-walk-initialization-for-lts-problem">Random Walk Initialization for LTS Problem</h4>
<p>A <em>random walk</em> approach was utilized within the PINNs framework to efficiently solve variations of the LTS problem under different boundary conditions. After successfully training the network for a base case (e.g., with <span class="math inline">\(x_2(t_f) = 5.0\)</span>), the trained weights were saved. These weights capture meaningful features and the underlying dynamics of the problem corresponding to the given boundary condition.</p>
<p>For a slightly perturbed case such as <span class="math inline">\(x_2(t_f) = 4.9\)</span>, instead of retraining the network from random initialization, the saved weights were reused to initialize the network. This reuse significantly reduced the number of iterations required for convergence. The network adapted quickly to the new scenario since the dynamics remained similar, and the pre-trained weights already encoded a near-optimal structure of the solution. This process can be interpreted as performing a “random walk” in the parameter space progressively stepping from known solutions to nearby perturbed cases.</p>
<p>Furthermore, for a range of other perturbations in <span class="math inline">\(x_2(t_f)\)</span>, a linear interpolation of weights from nearby trained cases was used to generate initial guesses. These interpolated weights provided good initialization even in untrained regions of the parameter space, again accelerating convergence and improving training stability.</p>
<p>In essence, this method acts as a time-saving mechanism, instead of solving each variation from scratch, which is computationally intensive, the PINNs leverage prior knowledge through a random walk strategy. This greatly enhances training efficiency and enables real-time adaptability in solving trajectory Optimization problems such as LTS, which is evident in the below figure.</p>
<div id="fig-ch3-interpolation-results" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch3-interpolation-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ch3-interpolation-results" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ch3-fe-eval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ch3-fe-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_imgs/ppt_FE_intre.png" class="img-fluid figure-img" data-ref-parent="fig-ch3-interpolation-results">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ch3-fe-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Number of Function Evaluations.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ch3-interpolation-results" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ch3-train-time" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ch3-train-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_imgs/ppt_time_intre.png" class="img-fluid figure-img" data-ref-parent="fig-ch3-interpolation-results">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ch3-train-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Time for Training.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-ch3-interpolation-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7
</figcaption>
</figure>
</div>
</section>
<section id="recursive-weight-interpolation-procedure" class="level4">
<h4 class="anchored" data-anchor-id="recursive-weight-interpolation-procedure">Recursive Weight Interpolation Procedure</h4>
<p>The interpolation approach is based on perturbing the final state condition <span class="math inline">\(x_2(t_f)\)</span> and utilizing the learned weights to extrapolate weights for further perturbations.</p>
<ul>
<li><p>The first perturbation is applied with <span class="math inline">\(\Delta x_2(t_f) = -0.1\)</span>, i.e., <span class="math inline">\(x_2(t_f) = 4.9\)</span>. The network is trained using this modified final state by incorporating it into the loss function.</p></li>
<li><p>This network is initialized using the base weights (corresponding to <span class="math inline">\(x_2(t_f) = 5.0\)</span>) and trained with the same stopping criterion as the base model. The loss drops below <span class="math inline">\(10^{-4}\)</span> within 300 iterations, indicating that the base weights significantly aided faster convergence. The network successfully adapted to the new final state with a much smaller error compared to training from scratch.</p></li>
<li><p>Once the network is trained for the perturbed final state <span class="math inline">\(x_2(t_f) = 4.9\)</span>, the interpolation process is extended recursively to generate weights for additional perturbations.</p></li>
</ul>
<p>The core idea is to use a linear interpolation formula to predict new weights:</p>
<p><span id="eq-ch3-interpolation"><span class="math display">\[
w_{\text{new}} = m \cdot x_{2\text{(tf,new)}} + b
\tag{38}\]</span></span></p>
<p>where:</p>
<p><span id="eq-ch3-interpolation-slope"><span class="math display">\[
m = \frac{w_2 - w_1}{x_{2\text{(tf,2)}} - x_{2\text{(tf,1)}}}, \quad b = w_1 - m \cdot x_{2\text{(tf,1)}}
\tag{39}\]</span></span></p>
<ul>
<li><p>The weights corresponding to <span class="math inline">\(x_2(t_f) = 5.0\)</span> and <span class="math inline">\(x_2(t_f) = 4.9\)</span> are used to extrapolate the weights for <span class="math inline">\(x_2(t_f) = 4.8\)</span>.</p></li>
<li><p>After verifying the performance of the network at <span class="math inline">\(x_2(t_f) = 4.8\)</span>, the weights for <span class="math inline">\(x_2(t_f) = 4.9\)</span> and <span class="math inline">\(4.8\)</span> are used to extrapolate for <span class="math inline">\(x_2(t_f) = 4.7\)</span>, and so on.</p></li>
<li><p>This recursive interpolation continues by always using the most recent two trained or extrapolated weight sets, i.e.,</p></li>
</ul>
<p><span id="eq-ch3-recursive"><span class="math display">\[
\text{Use } (w_{x_2 = 4.8}, w_{x_2 = 4.7}) \rightarrow w_{x_2 = 4.6}, \quad \text{and so on,}
\tag{40}\]</span></span></p>
<p>until the final state condition <span class="math inline">\(x_2(t_f) = 4.0\)</span> is reached.</p>
<ul>
<li><p>A similar process is carried out in the forward direction. After training the network at <span class="math inline">\(x_2(t_f) = 5.1\)</span>, the weights corresponding to <span class="math inline">\(x_2(t_f) = 5.0\)</span> and <span class="math inline">\(5.1\)</span> are used to extrapolate for <span class="math inline">\(x_2(t_f) = 5.2\)</span>.</p></li>
<li><p>This forward recursive interpolation is repeated until <span class="math inline">\(x_2(t_f) = 6.0\)</span> is reached.</p></li>
<li><p>At each step, the accuracy of interpolated weights is evaluated by comparing them with weights obtained through direct training for the corresponding final state condition.</p></li>
</ul>
</section>
</section>
<section id="effect-of-activation-function-on-model-performance" class="level3">
<h3 class="anchored" data-anchor-id="effect-of-activation-function-on-model-performance">Effect of Activation Function on Model Performance</h3>
<p>To investigate the role of activation functions in learning-based control tasks, we evaluate three variants: the standard Tanh, Layer-wise Locally Adaptive Activation Functions (L-LAAF) <span class="citation" data-cites="jagtap2022deep">[@jagtap2022deep]</span>, and RAAF, implemented using the Rowdy formulation. These functions are tested in identical training setups to ensure fairness in comparison.</p>
<p>Each model is trained under the same initialization, training data, and stopping criteria. The goal is to assess how these activation functions impact convergence, stability, and the network’s ability to generalize across perturbed final state conditions.</p>
<p><strong>1. Accuracy Comparison (Mean Squared Error)</strong></p>
<p>The Mean Squared Error (MSE) for key variables—state components <span class="math inline">\(x_1, x_2, x_3, x_4\)</span>, control input <span class="math inline">\(u\)</span>, and final time <span class="math inline">\(t_f\)</span>—is computed post-training. The results are summarized in the table below:</p>
<div id="tbl-ch3-mse-activation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch3-mse-activation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Comparison of MSE for different activation functions
</figcaption>
<div aria-describedby="tbl-ch3-mse-activation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">RAAF</th>
<th style="text-align: right;">L-LAAF</th>
<th style="text-align: right;">Tanh</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(x_1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2.10 \times 10^{-9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.74 \times 10^{-8}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(3.01 \times 10^{-9}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(x_2\)</span></td>
<td style="text-align: right;"><span class="math inline">\(3.98 \times 10^{-9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(3.56 \times 10^{-9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(4.44 \times 10^{-9}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(x_3\)</span></td>
<td style="text-align: right;"><span class="math inline">\(7.03 \times 10^{-9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(9.57 \times 10^{-8}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(5.52 \times 10^{-8}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(x_4\)</span></td>
<td style="text-align: right;"><span class="math inline">\(7.61 \times 10^{-9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(6.07 \times 10^{-8}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(6.72 \times 10^{-8}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Control <span class="math inline">\(u\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2.01 \times 10^{-6}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.69 \times 10^{-5}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2.34 \times 10^{-5}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Final Time <span class="math inline">\(t_f\)</span></td>
<td style="text-align: right;"><span class="math inline">\(8.56 \times 10^{-7}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(8.06 \times 10^{-7}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.89 \times 10^{-6}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>RAAF yields the lowest MSE across most variables, especially in control and states <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, indicating strong learning and generalization. L-LAAF performs well, particularly in final time <span class="math inline">\(t_f\)</span>, but exhibits higher errors in control and velocity states (<span class="math inline">\(x_3\)</span>, <span class="math inline">\(x_4\)</span>). In contrast, <strong>Tanh</strong> shows the highest error in control and final time, suggesting less adaptability to dynamic conditions.</p>
<p>We also compare the number of function evaluations and the total training time required for each activation:</p>
<div id="tbl-ch3-fe-time" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch3-fe-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Comparison of Function Evaluations and Training Time
</figcaption>
<div aria-describedby="tbl-ch3-fe-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Tanh</th>
<th style="text-align: right;">L-LAAF</th>
<th style="text-align: right;">RAAF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Function Evaluations</td>
<td style="text-align: right;">56625</td>
<td style="text-align: right;">56354</td>
<td style="text-align: right;">57871</td>
</tr>
<tr class="even">
<td style="text-align: left;">Training Time (s)</td>
<td style="text-align: right;">782.23</td>
<td style="text-align: right;">1062.65</td>
<td style="text-align: right;">4637.72</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Tanh and L-LAAF are computationally cheaper, requiring fewer function evaluations and less training time. In contrast, RAAF takes significantly longer to train, likely due to the complexity of its adaptive mechanism. Despite the higher computational cost, RAAF delivers superior accuracy, indicating a trade-off between computational expense and learning performance. The choice of activation function thus plays a crucial role in determining both learning accuracy and computational efficiency. While RAAF achieves the best accuracy, it comes with greater complexity, whereas L-LAAF offers a balanced trade-off and Tanh serves as a baseline with minimal computational demand.</p>
</section>
<section id="simplified-lts-model-with-trainable-parameters" class="level3">
<h3 class="anchored" data-anchor-id="simplified-lts-model-with-trainable-parameters">Simplified LTS Model with Trainable Parameters</h3>
<p>In the original trajectory optimization framework using LTS, the control input <span class="math inline">\(u\)</span> is computed indirectly from the costate variables, derived from Pontryagin’s Maximum Principle. Specifically, the optimal control law is given by:</p>
<p><span id="eq-ch3-original-control"><span class="math display">\[
u(t) = \tan^{-1}\left(\frac{\lambda_4(t)}{\lambda_3(t)}\right)
\tag{41}\]</span></span></p>
<p>This requires the neural network to output not only the state variables <span class="math inline">\(x(t), y(t), u(t), v(t)\)</span>, but also the costate variables <span class="math inline">\(\lambda_1(t), \lambda_2(t), \lambda_3(t), \lambda_4(t)\)</span>, resulting in a total of 8 outputs.</p>
<p><strong>Proposed Approach:</strong></p>
<p>We propose a simplified and more efficient formulation that avoids predicting costate variables altogether. Leveraging the analytical structure of the LTS problem, the optimal control <span class="math inline">\(u(t)\)</span> is known to follow the form:</p>
<p><span id="eq-ch3-simplified-control"><span class="math display">\[
u(t) = \tan^{-1} \left( \frac{c_1}{c_2} + \frac{c_3}{c_2} t \right)
\tag{42}\]</span></span></p>
<p>Here, <span class="math inline">\(c_1, c_2, c_3\)</span> are problem-dependent constants. In the proposed method, we treat these constants as <em>trainable parameters</em> within the neural network. The network now only needs to output the 4 state variables.</p>
<p>The control input <span class="math inline">\(u(t)\)</span> is computed using the parameterized control law in Equation, bypassing the need to estimate costates.</p>
<p><strong>Advantages of This Simplification:</strong></p>
<ul>
<li><strong>Reduced Network Complexity:</strong> By eliminating the need to predict costates, the network output size is halved—from 8 outputs to 4.</li>
<li><strong>Improved Training Efficiency:</strong> With fewer outputs and a structured control law, the learning problem becomes easier to optimize.</li>
<li><strong>Faster Convergence:</strong> The model converges faster due to fewer trainable outputs and the use of domain-specific knowledge embedded in the control law.</li>
<li><strong>Interpretability:</strong> The learned parameters <span class="math inline">\(c_1, c_2, c_3\)</span> provide insights into the structure of the optimal control, enhancing model transparency.</li>
</ul>
<p>The constants <span class="math inline">\(c_1, c_2, c_3\)</span> are learned alongside the network weights during training. During forward passes, <span class="math inline">\(u(t)\)</span> is computed directly from the equation using the current value of time <span class="math inline">\(t\)</span> and the learned parameters.</p>
<p>This approach tightly couples the control structure with the known analytical solution form, reducing the burden on the network and improving generalization. It exemplifies how hybridizing physics-based insight with learning-based models can yield both performance and interpretability benefits.</p>
<div id="tbl-ch3-simplified" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch3-simplified-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Error comparison between original RAAF and Simplified LTS: RAAF model.
</figcaption>
<div aria-describedby="tbl-ch3-simplified-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">RAAF</th>
<th style="text-align: right;">Simplified LTS: RAAF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">State 1 Error</td>
<td style="text-align: right;"><span class="math inline">\(2.1008 \times 10^{-9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(4.3835 \times 10^{-9}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">State 2 Error</td>
<td style="text-align: right;"><span class="math inline">\(3.9782 \times 10^{-9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(4.5787 \times 10^{-9}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">State 3 Error</td>
<td style="text-align: right;"><span class="math inline">\(7.0327 \times 10^{-9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(5.0759 \times 10^{-9}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">State 4 Error</td>
<td style="text-align: right;"><span class="math inline">\(7.6105 \times 10^{-9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(7.8337 \times 10^{-9}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Control Error</td>
<td style="text-align: right;"><span class="math inline">\(2.0105 \times 10^{-6}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(3.2782 \times 10^{-8}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Error in <span class="math inline">\(t_f\)</span></td>
<td style="text-align: right;"><span class="math inline">\(8.5635 \times 10^{-7}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.5023 \times 10^{-7}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The simplified LTS model maintains low state errors while significantly reducing the control error. Notably, the training time of the simplified model is <span class="math inline">\(2276.0\,\text{s}\)</span>, which is approximately half that of the original RAAF model. Additionally, the number of function evaluations is reduced to <span class="math inline">\(57477\)</span>, highlighting the efficiency of the proposed approach. This trade-off between model simplicity and performance effectively reduces network complexity and improves computational efficiency without compromising accuracy.</p>
</section>
<section id="limitations-with-the-pinns-method-for-ocp" class="level3">
<h3 class="anchored" data-anchor-id="limitations-with-the-pinns-method-for-ocp">Limitations with the PINNs Method for OCP</h3>
<p>As the number of states increases in an optimal control problem—for instance, from four to five by including an additional state such as the pitch angle and its corresponding ODE—the total loss during PINN training has been observed to diverge. This divergence is largely due to the added complexity introduced by the additional differential constraints, which significantly increases the number of residual terms the network must learn to satisfy. Each new state variable contributes both a state ODE and its associated costate equation in the Hamiltonian formalism, effectively doubling the number of ODE constraints. Consequently, the loss function becomes composed of many competing objectives, such as the state dynamics, costate dynamics, and boundary/initial conditions, which can conflict during Optimization.</p>
<p>This issue has been identified in the literature as a major limitation in PINN-based methods for optimal control. Mowlavi and Nabi <span class="citation" data-cites="mowlavi2022">[@mowlavi2022]</span> highlighted that in PDE-constrained optimal control problems, the presence of multiple differential constraints—especially when each comes with a state and costate component—can destabilize training due to the imbalance in the loss function. Similarly, Barry-Straume et al. <span class="citation" data-cites="barry2022controlpinns">[@barry2022controlpinns]</span> observed that as more equations are embedded into the PINN loss (e.g., due to additional state variables), the learning dynamics degrade, resulting in either stagnation or divergence of the total loss. Moreover, New et al. <span class="citation" data-cites="new2022">[@new2022]</span> showed empirically that increasing the number of coupled ODEs, even in relatively simple settings, leads to poor convergence behavior due to the ill-conditioning of the Optimization landscape and vanishing or exploding gradients.</p>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/kiranaralikatti\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Trajectory Optimization using Deep Neural Network</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Physics-Informed Neural Networks Architecture</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Physics-Informed Neural Networks (PINNs) are a class of deep learning models designed to solve ordinary and partial differential equations (ODEs and PDEs) by incorporating physical laws directly into the neural network training process. Unlike traditional numerical methods that rely on mesh-based discretization, PINNs embed the governing equations as soft constraints into the loss function, enabling mesh-free, data-efficient, and interpretable solutions <span class="co">[</span><span class="ot">@raissi2019physics; @karniadakis2021physics</span><span class="co">]</span>.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>The key idea behind PINNs is to construct a neural network that approximates the solution to a differential equation while minimizing a composite loss function. This loss typically includes two components: (i) the residuals of the governing equations, which enforce the physical constraints, and (ii) the error at initial and boundary conditions. By training the network to reduce these terms simultaneously, PINNs produce solutions that respect both data and physics.</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>PINNs offer significant advantages in solving complex and high-dimensional problems in fields such as fluid dynamics, heat conduction, elasticity, and optimal control <span class="co">[</span><span class="ot">@cuomo2022scientific</span><span class="co">]</span>. Their ability to encode prior knowledge in the form of differential operators improves generalization and stability, especially when observational data are sparse or noisy. Recent advances have extended PINNs to handle stiff systems, multi-physics problems, and inverse modeling tasks, showcasing their versatility and growing importance in scientific computing <span class="co">[</span><span class="ot">@wang2021understanding; @mao2020physics</span><span class="co">]</span>. Furthermore, innovations in adaptive activation functions, domain decomposition, and transfer learning continue to enhance their accuracy and scalability <span class="co">[</span><span class="ot">@mcclenny2020self; @shukla2021parallel</span><span class="co">]</span>.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">### PINN Formulation</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>Consider a general first-order system of ordinary differential equations given by:</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>\dot{\mathbf{x}}(t) = \mathbf{f}(\mathbf{x}(t), t), \quad t \in <span class="co">[</span><span class="ot">0, t_f</span><span class="co">]</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-pinn-ode}</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>where $\mathbf{x}(t) \in \mathbb{R}^n$ is the state vector, and $\mathbf{f} : \mathbb{R}^n \times \mathbb{R} \rightarrow \mathbb{R}^n$ is a known (possibly nonlinear) function describing the system dynamics. The system is subject to an initial condition:</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>\mathbf{x}(0) = \mathbf{x}_0.</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-pinn-ic}</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>In the PINN framework, the solution $\mathbf{x}(t)$ is approximated by a neural network $\mathbf{x}_{\theta}(t)$, where $\theta$ represents the trainable parameters of the network.</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">### Loss Function of PINNs</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>The total loss function used to train the PINN is composed of two terms: the residual loss and the initial condition loss. It is defined as:</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>\mathcal{L}_{\text{PINN}} = \omega_1 \mathcal{L}_{\text{residual}} + \omega_2 \mathcal{L}_{\text{IC}},</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-pinn-loss}</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>where $\omega_1$ and $\omega_2$ are weighting coefficients that balance the enforcement of the system dynamics and the initial condition, where $\sum_{i=0}^{N}\omega_i = 1$</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>The residual loss is computed over a set of $N$ collocation points $<span class="sc">\{</span>t_i<span class="sc">\}</span>_{i=1}^{N} \subset <span class="co">[</span><span class="ot">0, t_f</span><span class="co">]</span>$:</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>\mathcal{L}_{\text{residual}} = \frac{1}{N} \sum_{i=1}^{N} \left\| \frac{d}{dt} \mathbf{x}_{\theta}(t_i) - \mathbf{f}(\mathbf{x}_{\theta}(t_i), t_i) \right<span class="sc">\|</span>^2.</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-residual-loss}</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>The initial condition loss ensures that the predicted trajectory starts at the correct initial value:</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>\mathcal{L}_{\text{IC}} = \left\| \mathbf{x}_{\theta}(0) - \mathbf{x}_0 \right<span class="sc">\|</span>^2.</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-ic-loss}</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>This formulation ensures that the learned function $\mathbf{x}_{\theta}(t)$ adheres to both the physics (via the ODE residual) and the given initial condition.</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="fu">### Network Architecture</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>A typical PINN architecture consists of:</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Input Layer:** Receives input variables such as time, spatial coordinates, or parameters.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Hidden Layers:** Multiple fully connected layers using nonlinear activation functions such as Tanh or ReLU to learn the functional mapping.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Output Layer:** Produces the predicted solution $\mathbf{x}_{\theta}(t) \in \mathbb{R}^n$.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>This architecture is flexible and can be adapted to accommodate multiple outputs, complex nonlinearities, or additional inputs such as control parameters or auxiliary variables.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="fu">### Training Procedure</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>Training a PINN involves minimizing the loss function $\mathcal{L}_{\text{PINN}}$ using gradient-based optimization methods such as stochastic gradient descent (SGD) or Adam. The time derivatives of the neural network outputs are computed via automatic differentiation. During each iteration, gradients of the loss with respect to the network parameters $\theta$ are computed and used to update the model. The goal is to simultaneously minimize the equation residuals and enforce the boundary/initial conditions.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>!<span class="co">[</span><span class="ot">PINNs architecture [@cuomo2022scientific]</span><span class="co">](Chapter3_imgs/pinn_model.PNG)</span>{#fig-ch3-pinn-architecture width="75%"}</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="fu">### Solving Coupled ODEs</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>Coupled ODE systems frequently appear in scientific and engineering contexts such as trajectory optimization, chemical kinetics and multi-body dynamics. These systems consist of multiple interdependent differential equations that must be solved simultaneously.</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>PINNs handle coupled systems by using a NN with multiple outputs corresponding to each component of the state vector. The residuals of all coupled equations are computed and minimized together, while initial or boundary conditions for each state variable are incorporated into the loss function. This approach enables the network to learn solutions that satisfy the entire coupled system consistently.</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="fu">### Advantages and Challenges</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>PINNs offer several advantages. By embedding prior physical knowledge, PINNs significantly reduce the need for large labeled datasets, thereby improving data efficiency <span class="co">[</span><span class="ot">@raissi2019physics; @karniadakis2021physics</span><span class="co">]</span>. Moreover, the solutions produced are physically consistent, which enhances generalization, even in regions beyond the training data <span class="co">[</span><span class="ot">@cuomo2022scientific</span><span class="co">]</span>. Another key benefit is their mesh-free nature, eliminating the need for mesh generation or discretization, which simplifies implementation for complex geometries <span class="co">[</span><span class="ot">@raissi2019physics</span><span class="co">]</span>.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>Despite these benefits, several challenges remain. Training PINNs for stiff or highly nonlinear systems often suffers from gradient imbalance and instability, which can impede convergence <span class="co">[</span><span class="ot">@wang2021understanding; @lu2021deepxde</span><span class="co">]</span>. Additionally, selecting appropriate weighting factors for different loss components, such as residual and boundary condition losses, is nontrivial and can significantly affect performance <span class="co">[</span><span class="ot">@mcclenny2020self</span><span class="co">]</span>. The computational cost is another consideration, as training deep neural networks with automatic differentiation can be resource-intensive and time-consuming <span class="co">[</span><span class="ot">@shukla2021parallel</span><span class="co">]</span>.</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>Recent advances have addressed some of these challenges through methods such as adaptive activation functions, residual-based adaptive sampling, transfer learning, and domain decomposition, which improve training stability and efficiency <span class="co">[</span><span class="ot">@mcclenny2020self; @shukla2021parallel; @lu2021deepxde</span><span class="co">]</span>.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="fu">## ODEs Solution using PINNs</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scalar Trajectory Optimization</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>We consider an optimal control problem given in <span class="co">[</span><span class="ot">@pinch1995optimal</span><span class="co">]</span> example 4.3, involving a linear first-order dynamical system, where the state $x(t)$ evolves according to the control input $u(t)$ through the relation $\dot{x}(t) = -x(t) + u(t)$. The goal is to drive the system from the initial condition $x(0) = 0$ to the final state $x(1) = 2$ over the fixed time interval $t \in <span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span>$. To achieve this, we aim to determine the optimal control $u(t)$ that minimizes the quadratic cost functional, which penalizes both the magnitude of the state and the control effort over time. This cost functional captures the trade-off between maintaining the state close to the origin and minimizing the energy or effort required for control.</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>The system dynamics, boundary conditions, and cost functional are given as:</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>\dot{x}(t) &amp;= -x(t) + u(t), &amp;&amp; \text{(System dynamics)} <span class="sc">\\</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>x(0) &amp;= 0, \quad x(1) = 2, &amp;&amp; \text{(Boundary conditions)} <span class="sc">\\</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>J &amp;= \frac{1}{2} \int_0^1 \left( 3x^2(t) + u^2(t) \right) \, dt. &amp;&amp; \text{(Cost functional)}</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-problem}</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>The Hamiltonian</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>H = \frac{3}{2} x^2 + \frac{1}{2} u^2 + \lambda (-x + u).</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-hamiltonian}</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>There is no constraint on $u$, so to maximize $H$ we consider $\frac{\partial H}{\partial u}$.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>\frac{\partial H}{\partial u} = -u + \lambda \quad \text{and} \quad \frac{\partial^2 H}{\partial u^2} = -1.</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-hu}</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>So $H$ is maximized when $u = \lambda$ and the corresponding state equation is</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>\dot{x} = -x + \lambda</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-state-ode}</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>and $\lambda$ satisfies</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>\dot{\lambda} = -\frac{\partial H}{\partial x} = 3x + \lambda.</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-costate-ode}</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>Thus, $\ddot{x} = 4x$ and $\lambda = \dot{x} + x$, giving</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>x = A \sinh(2t + \alpha)</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-x-sol}</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>and</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>\lambda = u^* = A\left(2 \cosh(2t + \alpha) + \sinh(2t + \alpha)\right).</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-lambda}</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>The end conditions on $x$ give $\alpha = 0$ and $A = 2/\sinh 2$. Thus, the optimal control is</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>u^* = \frac{2(2 \cosh 2t + \sinh 2t)}{\sinh 2}.</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-u-optimal}</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>\dot{x}(t) = -x(t) + \lambda(t), &amp;&amp; \text{(State ODE)}<span class="sc">\\</span></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>\dot{\lambda}(t) = 3x(t) + \lambda(t), &amp;&amp; \text{(Costate ODE)}<span class="sc">\\</span></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-state-costate}</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Loss Function</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>In the PINNs framework, the state and costate equations are enforced through a loss that penalizes both the ODE residuals and the boundary conditions.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>**Residual Loss.**</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>\mathcal{L}_{\text{residual}} = \frac{1}{N} \sum_{i=1}^{N} </span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>\Big[ \big( \dot{x}_i + x_i - \lambda_i \big)^2 </span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>\big( \dot{\lambda}_i - 3x_i - \lambda_i \big)^2 \Big],</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-residual}</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>**Boundary Condition Loss.**</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>\mathcal{L}_{\text{BC}} = \tfrac{1}{2}(x(0)-0)^2 + (x(1)-2)^2,</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-bc}</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>**Total Loss.**</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>\mathcal{L}_{\text{PINN}} = w_1 \mathcal{L}_{\text{residual}} + w_2 \mathcal{L}_{\text{BC}}, </span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>\qquad \sum_{i=1}^{m} w_i = 1.</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-scalar-total-loss}</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="fu">### Linear Tangent Steering Problem</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>As explained in Section 2.3, the Linear Tangent Steering (LTS) problem is a time-optimal control problem that aims to minimize the transfer time of the vehicle while satisfying the system dynamics and boundary conditions.</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Hyperparameters</span></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>The PINNs model employs a fully connected feedforward neural network with 2 hidden layers, each containing 8 neurons. Training is conducted using the Adam optimizer with an initial learning rate of $10^{-3}$ over initial 1750 iterations and for next iterations 250 L-BFGS is employed. The total loss function uses weights $w_1 = 0.1$ and $w_2 = 0.9$ to prioritize boundary conditions. The model is trained with 100 domain collocation points and 2 boundary points at $t = 0$ and $t$. The architecture of the PINN designed for this problem is shown in @fig-ch3-pinn-scalar.</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="al">![PINNs Architecture for scalar problem](Chapter3_imgs/c22.PNG)</span>{#fig-ch3-pinn-scalar width="55%"}</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="fu">### Tanh Activation Function</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>The accuracy depends on the number of trainable parameters, so the number of the trainable parameters in the given architecture for Tanh activation function is given by the below calculation:</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>For each layer in the network:</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>\text{Number of Weights} &amp;= n_\text{current} \times n_\text{next}, <span class="sc">\\</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>\text{Number of Biases} &amp;= n_\text{next}, <span class="sc">\\</span></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>\text{Number of Parameters} &amp;= \text{Number of Weights} + \text{Number of Biases}.</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-param-count}</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>where $n_\text{current} =$ number of nodes in current layer and $n_\text{next} =$ number of nodes in next layer.</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>The total number of trainable parameters is the sum of the parameters across all layers.</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Layer <span class="pp">|</span> No of Weights <span class="pp">|</span> No of Biases <span class="pp">|</span> Total Parameters <span class="pp">|</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a><span class="pp">|:------|:-------------:|:------------:|:----------------:|</span></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Input to $1^{st}$ Hidden Layer <span class="pp">|</span> $1 \times 16 = 16$ <span class="pp">|</span> $16$ <span class="pp">|</span> $16 + 16 = 32$ <span class="pp">|</span></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $1^{st}$ Hidden to $2^{nd}$ Hidden Layer <span class="pp">|</span> $16 \times 16 = 256$ <span class="pp">|</span> $16$ <span class="pp">|</span> $256 + 16 = 272$ <span class="pp">|</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $2^{nd}$ Hidden to Output Layer <span class="pp">|</span> $16 \times 2 = 32$ <span class="pp">|</span> $2$ <span class="pp">|</span> $32 + 2 = 34$ <span class="pp">|</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Total** <span class="pp">|</span> $16 + 256 + 32 = 304$ <span class="pp">|</span> $16 + 16 + 2 = 34$ <span class="pp">|</span> $32 + 272 + 34 = 338$ <span class="pp">|</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>: Trainable Parameters per Layer (Tanh) {#tbl-ch3-trainable-tanh}</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>Thus, the total number of trainable parameters in the network is $338$.</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>Using the same network configuration with a Tanh activation function, the training process yielded a total loss of $\mathcal{L} = 1.038 \times 10^{-4}$. When compared against the analytical solution, the Root Mean Square (RMS) errors for the state and costate variables are $2.44 \times 10^{-3}$ and $3.64 \times 10^{-3}$. These results confirm the efficacy of the chosen network architecture and highlight the capability of the Tanh activation function in approximating the solution with a certain level of accuracy.</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a><span class="fu">### Rowdy Adaptive Activation Function (RAAF)</span></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>The development of sophisticated neural network architectures has been pivotal in advancing complex machine learning applications. One such innovation is the RAAF <span class="co">[</span><span class="ot">@ccelik2024optimal</span><span class="co">]</span>, designed to enhance the learning capability and generalization power of neural networks by integrating adaptive and oscillatory properties into traditional activation functions. This function introduces a novel approach to balancing expressiveness and training stability, utilizing modifications of standard activations such as the Tanh function.</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Modified Tanh Function</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>At the core of RAAF lies a modified Tanh function, mathematically expressed as:</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>\sigma(x; \alpha) = \frac{e^{\alpha x} - e^{-\alpha x}}{e^{\alpha x} + e^{-\alpha x}},</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-modified-tanh}</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>where $\alpha$ is a trainable parameter that scales the input, providing flexibility in the activation behavior. By allowing $\alpha$ to adapt during training, the network gains additional capacity to capture complex patterns in data. This adaptive feature accelerates convergence, particularly in the early training stages, by reshaping the gradient landscape to avoid saturation.</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Rowdy Adaptive Activation Function</span></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a>RAAF <span class="co">[</span><span class="ot">@jagtap2022deep</span><span class="co">]</span> extends this concept by combining the modified Tanh function with trigonometric terms, introducing oscillatory components that enrich the activation function's representational diversity:</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>\sigma_{\text{rowdy}}(x) = \sigma_{\text{base}}(x; \alpha) + \sum_{k=1}^N \beta_k \sin(k \omega x),</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-raaf}</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>where:</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>$\sigma_{\text{base}}(x; \alpha)$ represents the adaptive Tanh function.</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>$\beta_k$ and $\omega$ are trainable parameters that control the amplitude and frequency of the oscillations.</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>This design ensures smoother loss landscapes during training, reducing the risk of convergence to local minima. The oscillatory components are particularly useful in handling high-frequency variations in the data, enabling the model to generalize effectively across diverse input distributions.</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>For each layer in the network:</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>\text{Number of Weights} &amp;= n_\text{current} \times n_\text{next}, <span class="sc">\\</span></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>\text{Number of Biases} &amp;= n_\text{next}, <span class="sc">\\</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>\text{Number of Parameters} &amp;= \text{Weights} + \text{Biases}.</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-raaf-param-count}</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>where $n_\text{current} =$ number of nodes in current layer and $n_\text{next} =$ number of nodes in next layer.</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>Additionally, the RAAF adds:</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>\text{Parameters}_\text{rowdy} = n_\text{hidden} \times \text{RAAF parameters}</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-raaf-extra}</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>for each neuron in the hidden layers.</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>The total number of trainable parameters is the sum of all weights, biases, and RAAF-specific parameters.</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Layers <span class="pp">|</span> No of Weights <span class="pp">|</span> No of Biases <span class="pp">|</span> RAAF Parameters <span class="pp">|</span> Total Parameters <span class="pp">|</span></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="pp">|:-------|:-------------:|:------------:|:---------------:|:----------------:|</span></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> I/P to Hidden Layer <span class="pp">|</span> $1 \times 20 = 20$ <span class="pp">|</span> $20$ <span class="pp">|</span> $20 \times 3 = 60$ <span class="pp">|</span> $20 + 20 + 60 = 100$ <span class="pp">|</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Hidden to O/P Layer <span class="pp">|</span> $20 \times 2 = 40$ <span class="pp">|</span> $2$ <span class="pp">|</span> $0$ <span class="pp">|</span> $40 + 2 + 0 = 42$ <span class="pp">|</span></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Total** <span class="pp">|</span> $60$ <span class="pp">|</span> $22$ <span class="pp">|</span> $60$ <span class="pp">|</span> $142$ <span class="pp">|</span></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>: Trainable Parameters per Layer (RAAF) {#tbl-ch3-trainable-raaf}</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>Thus, the total number of trainable parameters in the network is: 142</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>Using the RAAF with one hidden layer and 20 nodes in the hidden layer, the training process achieved a total loss of $\mathcal{L} = 4.19 \times 10^{-5}$. When compared to the analytical solution, the RMS errors for the state and costate variables were $6.54 \times 10^{-5}$ and $5.84 \times 10^{-5}$. These results demonstrate the effectiveness of the RAAF in improving the accuracy of the solution while maintaining robust convergence properties with less number of trainable parameters.</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a><span class="al">![PINNs Solution using RAAF](Chapter3_imgs/comp_tah_rowdy.png)</span>{#fig-ch3-raaf-solution width="75%"}</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>::: {#fig-ch3-error-comparison layout-ncol=2}</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a><span class="al">![Total Error: Tanh.](Chapter3_imgs/tanh_error.png)</span>{#fig-ch3-tanh-error}</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a><span class="al">![Total Error: RAAF.](Chapter3_imgs/RAAF_error.png)</span>{#fig-ch3-raaf-error}</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>Comparison of the Total errors.</span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a><span class="fu">## Linear Tangent Steering Problem</span></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="fu">### PINNs Method</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Objective Function and Hamiltonian Derivation</span></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>The objective of the LTS problem is to minimize the final time $t_f$. Thus, the performance index (objective function) is:</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>J = \int_{0}^{t_f} 1 \, dt = t_f.</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-objective}</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>According to Pontryagin's Maximum Principle, we define the Hamiltonian $\mathcal{H}$ as:</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a>\mathcal{H} = 1 + \lambda_1 \dot{x}_1 + \lambda_2 \dot{x}_2 + \lambda_3 \dot{x}_3 + \lambda_4 \dot{x}_4.</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-hamiltonian}</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>Substituting the expressions for the state derivatives:</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a>\mathcal{H} &amp;= 1 + \lambda_1 x_3 + \lambda_2 x_4 + \lambda_3 a \cos(u) + \lambda_4 a \sin(u).</span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-hamiltonian-sub}</span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Costate Equations</span></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a>The costate dynamics are obtained from:</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a>\dot{\lambda}_i = -\frac{\partial \mathcal{H}}{\partial x_i}, \quad i = 1,2,3,4.</span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-costate-general}</span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>Calculating the partial derivatives:</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a>\dot{\lambda}_1 &amp;= -\frac{\partial \mathcal{H}}{\partial x_1} = 0, <span class="sc">\\</span></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a>\dot{\lambda}_2 &amp;= -\frac{\partial \mathcal{H}}{\partial x_2} = 0, <span class="sc">\\</span></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>\dot{\lambda}_3 &amp;= -\frac{\partial \mathcal{H}}{\partial x_3} = -\lambda_1, <span class="sc">\\</span></span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>\dot{\lambda}_4 &amp;= -\frac{\partial \mathcal{H}}{\partial x_4} = -\lambda_2.</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-costate}</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Optimal Control Law</span></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>The optimal control $u^*(t)$ minimizes the Hamiltonian with respect to the control input $u(t)$:</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a>u^*(t) = \arg\min_u \mathcal{H} = \arg\min_u \left( \lambda_3 a \cos(u) + \lambda_4 a \sin(u) \right).</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-optimal-control}</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a>This expression can be rewritten as:</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a>\mathcal{H}_{u} = a \left( \lambda_3 \cos(u) + \lambda_4 \sin(u) \right).</span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-hu}</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a>To minimize $\mathcal{H}_u$, the optimal control is given by:</span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a>u^*(t) = \tan^{-1}\left( \frac{\lambda_4(t)}{\lambda_3(t)} \right),</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-u-optimal}</span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Boundary Conditions</span></span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a>The boundary conditions for the LTS problem are:</span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Initial (fixed) conditions:**</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>x_1(0) = 0, \quad x_2(0) = 0, \quad x_3(0) = 0, \quad x_4(0) = 0</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-ic}</span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Final (partially fixed) conditions:**</span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a>x_2(t_f) = 5, \quad x_3(t_f) = 45, \quad x_4(t_f) = 0</span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-fc}</span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Transversality condition (due to free final state):**</span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a>\lambda_1(t_f) = 0 \quad \text{(since } x_1(t_f) \text{ is free)}</span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-transversality}</span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Loss Function for Domain</span></span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a>In the PINNs framework, the domain loss based on the residuals of the state and costate ODEs is defined as:</span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a>\mathcal{L}_{\text{residual}} = \frac{1}{N}\sum_{i=1}^{N} \left[ </span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a>\sum_{j=1}^{4} \left( \frac{d x_j}{d t}(t_i) - f_j(\mathbf{x}(t_i), u(t_i)) \right)^2 </span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>\sum_{j=1}^{4} \left( \frac{d \lambda_j}{d t}(t_i) - g_j(\boldsymbol{\lambda}(t_i)) \right)^2 </span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a>\right],</span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-domain-loss}</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a>where $f_j$ and $g_j$ denote the right-hand sides of the state and costate ODEs.</span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Loss Function for Boundary Conditions</span></span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a>The boundary loss enforces the known initial and final values, including the transversality condition:</span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a>\mathcal{L}_{\text{BC}} = &amp;\frac{1}{4} {\left( x_j(0) - x_{j,0} \right)^2 </span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>\left( x_2(t_f) - 5 \right)^2 </span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>\left( x_3(t_f) - 45 \right)^2 </span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>\left( x_4(t_f) - 0 \right)^2 </span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>\left( \lambda_1(t_f) \right)^2}</span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-bc-loss}</span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Total Loss Function</span></span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a>The complete loss function for training the PINN model becomes:</span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a>\mathcal{L}_{\text{PINN}} = w_1 \mathcal{L}_{\text{residual}} + w_2 \mathcal{L}_{\text{BC}},</span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-total-loss}</span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a>where $w_1 + w_2 = 1$ are hyperparameters controlling the balance between enforcing dynamics and boundary constraints.</span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Hyperparameters Tuning</span></span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a>For hyperparameter tuning, the training process employs a total of $30{,}000$ iterations, with a total loss threshold of $10^{-4}$ used as the primary stopping criterion. To enhance stability, a patience mechanism <span class="co">[</span><span class="ot">@sanchez2018real</span><span class="co">]</span> is incorporated: once the loss falls below $10^{-4}$, training continues for an additional $20$ iterations to ensure the loss consistently remains under the specified threshold.</span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a>The training procedure adopts a two-stage Optimization strategy. During the first stage, $90\%$ of the total iterations are executed using the **Adam** optimizer with a learning rate of $10^{-3}$, allowing for efficient convergence in the initial phase. In the second stage, the remaining $10\%$ of iterations utilize the **L-BFGS** optimizer for fine-tuning. The L-BFGS method is configured with a maximum of $50{,}000$ iterations, a history size of $50$, and a strong Wolfe line search condition.</span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a>This hybrid approach leverages the fast convergence properties of first-order methods during early training, while exploiting the higher accuracy of second-order methods in refining the solution as the loss approaches its minimum.</span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a>To place greater emphasis on control within the physics-informed loss, we include the term</span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a>\frac{\partial H}{\partial U} = 0 = -\lambda_3 \sin U + \lambda_4 \cos U</span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-lts-control-loss}</span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a>as part of the loss formulation.</span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a>As the analytical solution is available, the error of control is considered for tuning the network parameters. The below diagram shows how the error varied for the Tanh activation function for different number of hidden layers and nodes. The model with 3 hidden layers each with 60 nodes @fig-ch3-hp-control shows the best results, therefore, this model is used for further studies.</span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a><span class="al">![MSE error of Control for different nodes and layers](Chapter3_imgs/HP_control_diff_total_nodes.png)</span>{#fig-ch3-hp-control width="75%"}</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Variable <span class="pp">|</span> MSE <span class="pp">|</span></span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a><span class="pp">|:---------|----:|</span></span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_1$ <span class="pp">|</span> $3.01 \times 10^{-9}$ <span class="pp">|</span></span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_2$ <span class="pp">|</span> $4.44 \times 10^{-9}$ <span class="pp">|</span></span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_3$ <span class="pp">|</span> $5.52 \times 10^{-8}$ <span class="pp">|</span></span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_4$ <span class="pp">|</span> $6.72 \times 10^{-8}$ <span class="pp">|</span></span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Control $u$ <span class="pp">|</span> $2.34 \times 10^{-5}$ <span class="pp">|</span></span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Error final Time $\varepsilon_{t_f}$ <span class="pp">|</span> $1.89 \times 10^{-6}$ <span class="pp">|</span></span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a>: Mean Squared Error (MSE) for States, Control, and Final Time {#tbl-ch3-mse-lts}</span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a>In the LTS case, careful tuning enabled the network to achieve mean squared errors (MSE) as low as $10^{-5}$ for control. This level of accuracy demonstrates the model's ability to learn the underlying physics while maintaining smooth and stable control profiles.</span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a><span class="fu">### Weights Initialization and Interpolation</span></span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a><span class="al">![Weight Initialization and Interpolation](Chapter3_imgs/inter_process.PNG)</span>{#fig-ch3-interpolation width="75%"}</span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Random Walk Initialization for LTS Problem</span></span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a>A *random walk* approach was utilized within the PINNs framework to efficiently solve variations of the LTS problem under different boundary conditions. After successfully training the network for a base case (e.g., with $x_2(t_f) = 5.0$), the trained weights were saved. These weights capture meaningful features and the underlying dynamics of the problem corresponding to the given boundary condition.</span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-449"><a href="#cb1-449" aria-hidden="true" tabindex="-1"></a>For a slightly perturbed case such as $x_2(t_f) = 4.9$, instead of retraining the network from random initialization, the saved weights were reused to initialize the network. This reuse significantly reduced the number of iterations required for convergence. The network adapted quickly to the new scenario since the dynamics remained similar, and the pre-trained weights already encoded a near-optimal structure of the solution. This process can be interpreted as performing a "random walk" in the parameter space progressively stepping from known solutions to nearby perturbed cases.</span>
<span id="cb1-450"><a href="#cb1-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-451"><a href="#cb1-451" aria-hidden="true" tabindex="-1"></a>Furthermore, for a range of other perturbations in $x_2(t_f)$, a linear interpolation of weights from nearby trained cases was used to generate initial guesses. These interpolated weights provided good initialization even in untrained regions of the parameter space, again accelerating convergence and improving training stability.</span>
<span id="cb1-452"><a href="#cb1-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-453"><a href="#cb1-453" aria-hidden="true" tabindex="-1"></a>In essence, this method acts as a time-saving mechanism, instead of solving each variation from scratch, which is computationally intensive, the PINNs leverage prior knowledge through a random walk strategy. This greatly enhances training efficiency and enables real-time adaptability in solving trajectory Optimization problems such as LTS, which is evident in the below figure.</span>
<span id="cb1-454"><a href="#cb1-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-455"><a href="#cb1-455" aria-hidden="true" tabindex="-1"></a>::: {#fig-ch3-interpolation-results layout-ncol=2}</span>
<span id="cb1-456"><a href="#cb1-456" aria-hidden="true" tabindex="-1"></a><span class="al">![Number of Function Evaluations.](Chapter3_imgs/ppt_FE_intre.png)</span>{#fig-ch3-fe-eval}</span>
<span id="cb1-457"><a href="#cb1-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-458"><a href="#cb1-458" aria-hidden="true" tabindex="-1"></a><span class="al">![Time for Training.](Chapter3_imgs/ppt_time_intre.png)</span>{#fig-ch3-train-time}</span>
<span id="cb1-459"><a href="#cb1-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-460"><a href="#cb1-460" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-461"><a href="#cb1-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-462"><a href="#cb1-462" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Recursive Weight Interpolation Procedure</span></span>
<span id="cb1-463"><a href="#cb1-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-464"><a href="#cb1-464" aria-hidden="true" tabindex="-1"></a>The interpolation approach is based on perturbing the final state condition $x_2(t_f)$ and utilizing the learned weights to extrapolate weights for further perturbations.</span>
<span id="cb1-465"><a href="#cb1-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-466"><a href="#cb1-466" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The first perturbation is applied with $\Delta x_2(t_f) = -0.1$, i.e., $x_2(t_f) = 4.9$. The network is trained using this modified final state by incorporating it into the loss function.</span>
<span id="cb1-467"><a href="#cb1-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-468"><a href="#cb1-468" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>This network is initialized using the base weights (corresponding to $x_2(t_f) = 5.0$) and trained with the same stopping criterion as the base model. The loss drops below $10^{-4}$ within 300 iterations, indicating that the base weights significantly aided faster convergence. The network successfully adapted to the new final state with a much smaller error compared to training from scratch.</span>
<span id="cb1-469"><a href="#cb1-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-470"><a href="#cb1-470" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Once the network is trained for the perturbed final state $x_2(t_f) = 4.9$, the interpolation process is extended recursively to generate weights for additional perturbations.</span>
<span id="cb1-471"><a href="#cb1-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-472"><a href="#cb1-472" aria-hidden="true" tabindex="-1"></a>The core idea is to use a linear interpolation formula to predict new weights:</span>
<span id="cb1-473"><a href="#cb1-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-474"><a href="#cb1-474" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-475"><a href="#cb1-475" aria-hidden="true" tabindex="-1"></a>w_{\text{new}} = m \cdot x_{2\text{(tf,new)}} + b</span>
<span id="cb1-476"><a href="#cb1-476" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-interpolation}</span>
<span id="cb1-477"><a href="#cb1-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-478"><a href="#cb1-478" aria-hidden="true" tabindex="-1"></a>where:</span>
<span id="cb1-479"><a href="#cb1-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-480"><a href="#cb1-480" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-481"><a href="#cb1-481" aria-hidden="true" tabindex="-1"></a>m = \frac{w_2 - w_1}{x_{2\text{(tf,2)}} - x_{2\text{(tf,1)}}}, \quad b = w_1 - m \cdot x_{2\text{(tf,1)}}</span>
<span id="cb1-482"><a href="#cb1-482" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-interpolation-slope}</span>
<span id="cb1-483"><a href="#cb1-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-484"><a href="#cb1-484" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The weights corresponding to $x_2(t_f) = 5.0$ and $x_2(t_f) = 4.9$ are used to extrapolate the weights for $x_2(t_f) = 4.8$.</span>
<span id="cb1-485"><a href="#cb1-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-486"><a href="#cb1-486" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>After verifying the performance of the network at $x_2(t_f) = 4.8$, the weights for $x_2(t_f) = 4.9$ and $4.8$ are used to extrapolate for $x_2(t_f) = 4.7$, and so on.</span>
<span id="cb1-487"><a href="#cb1-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-488"><a href="#cb1-488" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>This recursive interpolation continues by always using the most recent two trained or extrapolated weight sets, i.e.,</span>
<span id="cb1-489"><a href="#cb1-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-490"><a href="#cb1-490" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-491"><a href="#cb1-491" aria-hidden="true" tabindex="-1"></a>\text{Use } (w_{x_2 = 4.8}, w_{x_2 = 4.7}) \rightarrow w_{x_2 = 4.6}, \quad \text{and so on,}</span>
<span id="cb1-492"><a href="#cb1-492" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-recursive}</span>
<span id="cb1-493"><a href="#cb1-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-494"><a href="#cb1-494" aria-hidden="true" tabindex="-1"></a>until the final state condition $x_2(t_f) = 4.0$ is reached.</span>
<span id="cb1-495"><a href="#cb1-495" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-496"><a href="#cb1-496" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A similar process is carried out in the forward direction. After training the network at $x_2(t_f) = 5.1$, the weights corresponding to $x_2(t_f) = 5.0$ and $5.1$ are used to extrapolate for $x_2(t_f) = 5.2$.</span>
<span id="cb1-497"><a href="#cb1-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-498"><a href="#cb1-498" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>This forward recursive interpolation is repeated until $x_2(t_f) = 6.0$ is reached.</span>
<span id="cb1-499"><a href="#cb1-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-500"><a href="#cb1-500" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>At each step, the accuracy of interpolated weights is evaluated by comparing them with weights obtained through direct training for the corresponding final state condition.</span>
<span id="cb1-501"><a href="#cb1-501" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-502"><a href="#cb1-502" aria-hidden="true" tabindex="-1"></a><span class="fu">### Effect of Activation Function on Model Performance</span></span>
<span id="cb1-503"><a href="#cb1-503" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-504"><a href="#cb1-504" aria-hidden="true" tabindex="-1"></a>To investigate the role of activation functions in learning-based control tasks, we evaluate three variants: the standard Tanh, Layer-wise Locally Adaptive Activation Functions (L-LAAF) <span class="co">[</span><span class="ot">@jagtap2022deep</span><span class="co">]</span>, and RAAF, implemented using the Rowdy formulation. These functions are tested in identical training setups to ensure fairness in comparison.</span>
<span id="cb1-505"><a href="#cb1-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-506"><a href="#cb1-506" aria-hidden="true" tabindex="-1"></a>Each model is trained under the same initialization, training data, and stopping criteria. The goal is to assess how these activation functions impact convergence, stability, and the network's ability to generalize across perturbed final state conditions.</span>
<span id="cb1-507"><a href="#cb1-507" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-508"><a href="#cb1-508" aria-hidden="true" tabindex="-1"></a>**1. Accuracy Comparison (Mean Squared Error)**</span>
<span id="cb1-509"><a href="#cb1-509" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-510"><a href="#cb1-510" aria-hidden="true" tabindex="-1"></a>The Mean Squared Error (MSE) for key variables—state components $x_1, x_2, x_3, x_4$, control input $u$, and final time $t_f$—is computed post-training. The results are summarized in the table below:</span>
<span id="cb1-511"><a href="#cb1-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-512"><a href="#cb1-512" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Variable <span class="pp">|</span> RAAF <span class="pp">|</span> L-LAAF <span class="pp">|</span> Tanh <span class="pp">|</span></span>
<span id="cb1-513"><a href="#cb1-513" aria-hidden="true" tabindex="-1"></a><span class="pp">|:---------|-----:|-------:|-----:|</span></span>
<span id="cb1-514"><a href="#cb1-514" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_1$ <span class="pp">|</span> $2.10 \times 10^{-9}$ <span class="pp">|</span> $1.74 \times 10^{-8}$ <span class="pp">|</span> $3.01 \times 10^{-9}$ <span class="pp">|</span></span>
<span id="cb1-515"><a href="#cb1-515" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_2$ <span class="pp">|</span> $3.98 \times 10^{-9}$ <span class="pp">|</span> $3.56 \times 10^{-9}$ <span class="pp">|</span> $4.44 \times 10^{-9}$ <span class="pp">|</span></span>
<span id="cb1-516"><a href="#cb1-516" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_3$ <span class="pp">|</span> $7.03 \times 10^{-9}$ <span class="pp">|</span> $9.57 \times 10^{-8}$ <span class="pp">|</span> $5.52 \times 10^{-8}$ <span class="pp">|</span></span>
<span id="cb1-517"><a href="#cb1-517" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_4$ <span class="pp">|</span> $7.61 \times 10^{-9}$ <span class="pp">|</span> $6.07 \times 10^{-8}$ <span class="pp">|</span> $6.72 \times 10^{-8}$ <span class="pp">|</span></span>
<span id="cb1-518"><a href="#cb1-518" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Control $u$ <span class="pp">|</span> $2.01 \times 10^{-6}$ <span class="pp">|</span> $1.69 \times 10^{-5}$ <span class="pp">|</span> $2.34 \times 10^{-5}$ <span class="pp">|</span></span>
<span id="cb1-519"><a href="#cb1-519" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Final Time $t_f$ <span class="pp">|</span> $8.56 \times 10^{-7}$ <span class="pp">|</span> $8.06 \times 10^{-7}$ <span class="pp">|</span> $1.89 \times 10^{-6}$ <span class="pp">|</span></span>
<span id="cb1-520"><a href="#cb1-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-521"><a href="#cb1-521" aria-hidden="true" tabindex="-1"></a>: Comparison of MSE for different activation functions {#tbl-ch3-mse-activation}</span>
<span id="cb1-522"><a href="#cb1-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-523"><a href="#cb1-523" aria-hidden="true" tabindex="-1"></a>RAAF yields the lowest MSE across most variables, especially in control and states $x_1$ and $x_2$, indicating strong learning and generalization. L-LAAF performs well, particularly in final time $t_f$, but exhibits higher errors in control and velocity states ($x_3$, $x_4$). In contrast, **Tanh** shows the highest error in control and final time, suggesting less adaptability to dynamic conditions.</span>
<span id="cb1-524"><a href="#cb1-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-525"><a href="#cb1-525" aria-hidden="true" tabindex="-1"></a>We also compare the number of function evaluations and the total training time required for each activation:</span>
<span id="cb1-526"><a href="#cb1-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-527"><a href="#cb1-527" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Metric <span class="pp">|</span> Tanh <span class="pp">|</span> L-LAAF <span class="pp">|</span> RAAF <span class="pp">|</span></span>
<span id="cb1-528"><a href="#cb1-528" aria-hidden="true" tabindex="-1"></a><span class="pp">|:-------|-----:|-------:|-----:|</span></span>
<span id="cb1-529"><a href="#cb1-529" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Function Evaluations <span class="pp">|</span> 56625 <span class="pp">|</span> 56354 <span class="pp">|</span> 57871 <span class="pp">|</span></span>
<span id="cb1-530"><a href="#cb1-530" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Training Time (s) <span class="pp">|</span> 782.23 <span class="pp">|</span> 1062.65 <span class="pp">|</span> 4637.72 <span class="pp">|</span></span>
<span id="cb1-531"><a href="#cb1-531" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-532"><a href="#cb1-532" aria-hidden="true" tabindex="-1"></a>: Comparison of Function Evaluations and Training Time {#tbl-ch3-fe-time}</span>
<span id="cb1-533"><a href="#cb1-533" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-534"><a href="#cb1-534" aria-hidden="true" tabindex="-1"></a>Tanh and L-LAAF are computationally cheaper, requiring fewer function evaluations and less training time. In contrast, RAAF takes significantly longer to train, likely due to the complexity of its adaptive mechanism. Despite the higher computational cost, RAAF delivers superior accuracy, indicating a trade-off between computational expense and learning performance. The choice of activation function thus plays a crucial role in determining both learning accuracy and computational efficiency. While RAAF achieves the best accuracy, it comes with greater complexity, whereas L-LAAF offers a balanced trade-off and Tanh serves as a baseline with minimal computational demand.</span>
<span id="cb1-535"><a href="#cb1-535" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-536"><a href="#cb1-536" aria-hidden="true" tabindex="-1"></a><span class="fu">### Simplified LTS Model with Trainable Parameters</span></span>
<span id="cb1-537"><a href="#cb1-537" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-538"><a href="#cb1-538" aria-hidden="true" tabindex="-1"></a>In the original trajectory optimization framework using LTS, the control input $u$ is computed indirectly from the costate variables, derived from Pontryagin's Maximum Principle. Specifically, the optimal control law is given by:</span>
<span id="cb1-539"><a href="#cb1-539" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-540"><a href="#cb1-540" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-541"><a href="#cb1-541" aria-hidden="true" tabindex="-1"></a>u(t) = \tan^{-1}\left(\frac{\lambda_4(t)}{\lambda_3(t)}\right)</span>
<span id="cb1-542"><a href="#cb1-542" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-original-control}</span>
<span id="cb1-543"><a href="#cb1-543" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-544"><a href="#cb1-544" aria-hidden="true" tabindex="-1"></a>This requires the neural network to output not only the state variables $x(t), y(t), u(t), v(t)$, but also the costate variables $\lambda_1(t), \lambda_2(t), \lambda_3(t), \lambda_4(t)$, resulting in a total of 8 outputs.</span>
<span id="cb1-545"><a href="#cb1-545" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-546"><a href="#cb1-546" aria-hidden="true" tabindex="-1"></a>**Proposed Approach:**</span>
<span id="cb1-547"><a href="#cb1-547" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-548"><a href="#cb1-548" aria-hidden="true" tabindex="-1"></a>We propose a simplified and more efficient formulation that avoids predicting costate variables altogether. Leveraging the analytical structure of the LTS problem, the optimal control $u(t)$ is known to follow the form:</span>
<span id="cb1-549"><a href="#cb1-549" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-550"><a href="#cb1-550" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-551"><a href="#cb1-551" aria-hidden="true" tabindex="-1"></a>u(t) = \tan^{-1} \left( \frac{c_1}{c_2} + \frac{c_3}{c_2} t \right)</span>
<span id="cb1-552"><a href="#cb1-552" aria-hidden="true" tabindex="-1"></a>$$ {#eq-ch3-simplified-control}</span>
<span id="cb1-553"><a href="#cb1-553" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-554"><a href="#cb1-554" aria-hidden="true" tabindex="-1"></a>Here, $c_1, c_2, c_3$ are problem-dependent constants. In the proposed method, we treat these constants as *trainable parameters* within the neural network. The network now only needs to output the 4 state variables.</span>
<span id="cb1-555"><a href="#cb1-555" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-556"><a href="#cb1-556" aria-hidden="true" tabindex="-1"></a>The control input $u(t)$ is computed using the parameterized control law in Equation, bypassing the need to estimate costates.</span>
<span id="cb1-557"><a href="#cb1-557" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-558"><a href="#cb1-558" aria-hidden="true" tabindex="-1"></a>**Advantages of This Simplification:**</span>
<span id="cb1-559"><a href="#cb1-559" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-560"><a href="#cb1-560" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Reduced Network Complexity:** By eliminating the need to predict costates, the network output size is halved—from 8 outputs to 4.</span>
<span id="cb1-561"><a href="#cb1-561" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Improved Training Efficiency:** With fewer outputs and a structured control law, the learning problem becomes easier to optimize.</span>
<span id="cb1-562"><a href="#cb1-562" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Faster Convergence:** The model converges faster due to fewer trainable outputs and the use of domain-specific knowledge embedded in the control law.</span>
<span id="cb1-563"><a href="#cb1-563" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Interpretability:** The learned parameters $c_1, c_2, c_3$ provide insights into the structure of the optimal control, enhancing model transparency.</span>
<span id="cb1-564"><a href="#cb1-564" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-565"><a href="#cb1-565" aria-hidden="true" tabindex="-1"></a>The constants $c_1, c_2, c_3$ are learned alongside the network weights during training. During forward passes, $u(t)$ is computed directly from the equation using the current value of time $t$ and the learned parameters.</span>
<span id="cb1-566"><a href="#cb1-566" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-567"><a href="#cb1-567" aria-hidden="true" tabindex="-1"></a>This approach tightly couples the control structure with the known analytical solution form, reducing the burden on the network and improving generalization. It exemplifies how hybridizing physics-based insight with learning-based models can yield both performance and interpretability benefits.</span>
<span id="cb1-568"><a href="#cb1-568" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-569"><a href="#cb1-569" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Metric <span class="pp">|</span> RAAF <span class="pp">|</span> Simplified LTS: RAAF <span class="pp">|</span></span>
<span id="cb1-570"><a href="#cb1-570" aria-hidden="true" tabindex="-1"></a><span class="pp">|:-------|-----:|---------------------:|</span></span>
<span id="cb1-571"><a href="#cb1-571" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> State 1 Error <span class="pp">|</span> $2.1008 \times 10^{-9}$ <span class="pp">|</span> $4.3835 \times 10^{-9}$ <span class="pp">|</span></span>
<span id="cb1-572"><a href="#cb1-572" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> State 2 Error <span class="pp">|</span> $3.9782 \times 10^{-9}$ <span class="pp">|</span> $4.5787 \times 10^{-9}$ <span class="pp">|</span></span>
<span id="cb1-573"><a href="#cb1-573" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> State 3 Error <span class="pp">|</span> $7.0327 \times 10^{-9}$ <span class="pp">|</span> $5.0759 \times 10^{-9}$ <span class="pp">|</span></span>
<span id="cb1-574"><a href="#cb1-574" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> State 4 Error <span class="pp">|</span> $7.6105 \times 10^{-9}$ <span class="pp">|</span> $7.8337 \times 10^{-9}$ <span class="pp">|</span></span>
<span id="cb1-575"><a href="#cb1-575" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Control Error <span class="pp">|</span> $2.0105 \times 10^{-6}$ <span class="pp">|</span> $3.2782 \times 10^{-8}$ <span class="pp">|</span></span>
<span id="cb1-576"><a href="#cb1-576" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Error in $t_f$ <span class="pp">|</span> $8.5635 \times 10^{-7}$ <span class="pp">|</span> $1.5023 \times 10^{-7}$ <span class="pp">|</span></span>
<span id="cb1-577"><a href="#cb1-577" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-578"><a href="#cb1-578" aria-hidden="true" tabindex="-1"></a>: Error comparison between original RAAF and Simplified LTS: RAAF model. {#tbl-ch3-simplified}</span>
<span id="cb1-579"><a href="#cb1-579" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-580"><a href="#cb1-580" aria-hidden="true" tabindex="-1"></a>The simplified LTS model maintains low state errors while significantly reducing the control error. Notably, the training time of the simplified model is $2276.0\,\text{s}$, which is approximately half that of the original RAAF model. Additionally, the number of function evaluations is reduced to $57477$, highlighting the efficiency of the proposed approach. This trade-off between model simplicity and performance effectively reduces network complexity and improves computational efficiency without compromising accuracy.</span>
<span id="cb1-581"><a href="#cb1-581" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-582"><a href="#cb1-582" aria-hidden="true" tabindex="-1"></a><span class="fu">### Limitations with the PINNs Method for OCP</span></span>
<span id="cb1-583"><a href="#cb1-583" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-584"><a href="#cb1-584" aria-hidden="true" tabindex="-1"></a>As the number of states increases in an optimal control problem—for instance, from four to five by including an additional state such as the pitch angle and its corresponding ODE—the total loss during PINN training has been observed to diverge. This divergence is largely due to the added complexity introduced by the additional differential constraints, which significantly increases the number of residual terms the network must learn to satisfy. Each new state variable contributes both a state ODE and its associated costate equation in the Hamiltonian formalism, effectively doubling the number of ODE constraints. Consequently, the loss function becomes composed of many competing objectives, such as the state dynamics, costate dynamics, and boundary/initial conditions, which can conflict during Optimization.</span>
<span id="cb1-585"><a href="#cb1-585" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-586"><a href="#cb1-586" aria-hidden="true" tabindex="-1"></a>This issue has been identified in the literature as a major limitation in PINN-based methods for optimal control. Mowlavi and Nabi <span class="co">[</span><span class="ot">@mowlavi2022</span><span class="co">]</span> highlighted that in PDE-constrained optimal control problems, the presence of multiple differential constraints—especially when each comes with a state and costate component—can destabilize training due to the imbalance in the loss function. Similarly, Barry-Straume et al. <span class="co">[</span><span class="ot">@barry2022controlpinns</span><span class="co">]</span> observed that as more equations are embedded into the PINN loss (e.g., due to additional state variables), the learning dynamics degrade, resulting in either stagnation or divergence of the total loss. Moreover, New et al. <span class="co">[</span><span class="ot">@new2022</span><span class="co">]</span> showed empirically that increasing the number of coupled ODEs, even in relatively simple settings, leads to poor convergence behavior due to the ill-conditioning of the Optimization landscape and vanishing or exploding gradients.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2025 Kiran M Aralikatti</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/kiranaralikatti/edit/main/DNN_Pipeline_for_TO/chapter_3.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/kiranaralikatti/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>